// Code generated by mockery v2.50.2. DO NOT EDIT.

package authregister

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

type IClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IClient) EXPECT() *IClient_Expecter {
	return &IClient_Expecter{mock: &_m.Mock}
}

// RegisterManagedInstance provides a mock function with given fields: ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson, provider
func (_m *IClient) RegisterManagedInstance(ctx context.Context, publicKey string, publicKeyType string, fingerprint string, iamRole string, tagsJson string, provider string) (string, error) {
	ret := _m.Called(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson, provider)

	if len(ret) == 0 {
		panic("no return value specified for RegisterManagedInstance")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) string); ok {
		r0 = rf(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson, provider)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClient_RegisterManagedInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterManagedInstance'
type IClient_RegisterManagedInstance_Call struct {
	*mock.Call
}

// RegisterManagedInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - publicKey string
//   - publicKeyType string
//   - fingerprint string
//   - iamRole string
//   - tagsJson string
//   - provider string
func (_e *IClient_Expecter) RegisterManagedInstance(ctx interface{}, publicKey interface{}, publicKeyType interface{}, fingerprint interface{}, iamRole interface{}, tagsJson interface{}, provider interface{}) *IClient_RegisterManagedInstance_Call {
	return &IClient_RegisterManagedInstance_Call{Call: _e.mock.On("RegisterManagedInstance", ctx, publicKey, publicKeyType, fingerprint, iamRole, tagsJson, provider)}
}

func (_c *IClient_RegisterManagedInstance_Call) Run(run func(ctx context.Context, publicKey string, publicKeyType string, fingerprint string, iamRole string, tagsJson string, provider string)) *IClient_RegisterManagedInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *IClient_RegisterManagedInstance_Call) Return(_a0 string, _a1 error) *IClient_RegisterManagedInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IClient_RegisterManagedInstance_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string) (string, error)) *IClient_RegisterManagedInstance_Call {
	_c.Call.Return(run)
	return _c
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
