// Code generated by mockery v2.50.2. DO NOT EDIT.

package authregister

import (
	context "context"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	mock "github.com/stretchr/testify/mock"
)

// ISsmSdk is an autogenerated mock type for the ISsmSdk type
type ISsmSdk struct {
	mock.Mock
}

type ISsmSdk_Expecter struct {
	mock *mock.Mock
}

func (_m *ISsmSdk) EXPECT() *ISsmSdk_Expecter {
	return &ISsmSdk_Expecter{mock: &_m.Mock}
}

// RegisterManagedInstance provides a mock function with given fields: ctx, input, optFns
func (_m *ISsmSdk) RegisterManagedInstance(ctx context.Context, input *ssm.RegisterManagedInstanceInput, optFns ...func(*ssm.Options)) (*ssm.RegisterManagedInstanceOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterManagedInstance")
	}

	var r0 *ssm.RegisterManagedInstanceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.RegisterManagedInstanceInput, ...func(*ssm.Options)) (*ssm.RegisterManagedInstanceOutput, error)); ok {
		return rf(ctx, input, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.RegisterManagedInstanceInput, ...func(*ssm.Options)) *ssm.RegisterManagedInstanceOutput); ok {
		r0 = rf(ctx, input, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RegisterManagedInstanceOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssm.RegisterManagedInstanceInput, ...func(*ssm.Options)) error); ok {
		r1 = rf(ctx, input, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISsmSdk_RegisterManagedInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterManagedInstance'
type ISsmSdk_RegisterManagedInstance_Call struct {
	*mock.Call
}

// RegisterManagedInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.RegisterManagedInstanceInput
//   - optFns ...func(*ssm.Options)
func (_e *ISsmSdk_Expecter) RegisterManagedInstance(ctx interface{}, input interface{}, optFns ...interface{}) *ISsmSdk_RegisterManagedInstance_Call {
	return &ISsmSdk_RegisterManagedInstance_Call{Call: _e.mock.On("RegisterManagedInstance",
		append([]interface{}{ctx, input}, optFns...)...)}
}

func (_c *ISsmSdk_RegisterManagedInstance_Call) Run(run func(ctx context.Context, input *ssm.RegisterManagedInstanceInput, optFns ...func(*ssm.Options))) *ISsmSdk_RegisterManagedInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*ssm.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*ssm.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*ssm.RegisterManagedInstanceInput), variadicArgs...)
	})
	return _c
}

func (_c *ISsmSdk_RegisterManagedInstance_Call) Return(_a0 *ssm.RegisterManagedInstanceOutput, _a1 error) *ISsmSdk_RegisterManagedInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISsmSdk_RegisterManagedInstance_Call) RunAndReturn(run func(context.Context, *ssm.RegisterManagedInstanceInput, ...func(*ssm.Options)) (*ssm.RegisterManagedInstanceOutput, error)) *ISsmSdk_RegisterManagedInstance_Call {
	_c.Call.Return(run)
	return _c
}

// NewISsmSdk creates a new instance of ISsmSdk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISsmSdk(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISsmSdk {
	mock := &ISsmSdk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
