// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	imds "github.com/aws/aws-sdk-go-v2/feature/ec2/imds"

	mock "github.com/stretchr/testify/mock"
)

// IEC2MdsSdkClient is an autogenerated mock type for the IEC2MdsSdkClient type
type IEC2MdsSdkClient struct {
	mock.Mock
}

type IEC2MdsSdkClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IEC2MdsSdkClient) EXPECT() *IEC2MdsSdkClient_Expecter {
	return &IEC2MdsSdkClient_Expecter{mock: &_m.Mock}
}

// GetMetadata provides a mock function with given fields: ctx, params, optFns
func (_m *IEC2MdsSdkClient) GetMetadata(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options)) (*imds.GetMetadataOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *imds.GetMetadataOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) (*imds.GetMetadataOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) *imds.GetMetadataOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetMetadataOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2MdsSdkClient_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type IEC2MdsSdkClient_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetMetadataInput
//   - optFns ...func(*imds.Options)
func (_e *IEC2MdsSdkClient_Expecter) GetMetadata(ctx interface{}, params interface{}, optFns ...interface{}) *IEC2MdsSdkClient_GetMetadata_Call {
	return &IEC2MdsSdkClient_GetMetadata_Call{Call: _e.mock.On("GetMetadata",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *IEC2MdsSdkClient_GetMetadata_Call) Run(run func(ctx context.Context, params *imds.GetMetadataInput, optFns ...func(*imds.Options))) *IEC2MdsSdkClient_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*imds.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*imds.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*imds.GetMetadataInput), variadicArgs...)
	})
	return _c
}

func (_c *IEC2MdsSdkClient_GetMetadata_Call) Return(_a0 *imds.GetMetadataOutput, _a1 error) *IEC2MdsSdkClient_GetMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2MdsSdkClient_GetMetadata_Call) RunAndReturn(run func(context.Context, *imds.GetMetadataInput, ...func(*imds.Options)) (*imds.GetMetadataOutput, error)) *IEC2MdsSdkClient_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegion provides a mock function with given fields: ctx, params, optFns
func (_m *IEC2MdsSdkClient) GetRegion(ctx context.Context, params *imds.GetRegionInput, optFns ...func(*imds.Options)) (*imds.GetRegionOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetRegion")
	}

	var r0 *imds.GetRegionOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) (*imds.GetRegionOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) *imds.GetRegionOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*imds.GetRegionOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2MdsSdkClient_GetRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegion'
type IEC2MdsSdkClient_GetRegion_Call struct {
	*mock.Call
}

// GetRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - params *imds.GetRegionInput
//   - optFns ...func(*imds.Options)
func (_e *IEC2MdsSdkClient_Expecter) GetRegion(ctx interface{}, params interface{}, optFns ...interface{}) *IEC2MdsSdkClient_GetRegion_Call {
	return &IEC2MdsSdkClient_GetRegion_Call{Call: _e.mock.On("GetRegion",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *IEC2MdsSdkClient_GetRegion_Call) Run(run func(ctx context.Context, params *imds.GetRegionInput, optFns ...func(*imds.Options))) *IEC2MdsSdkClient_GetRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*imds.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*imds.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*imds.GetRegionInput), variadicArgs...)
	})
	return _c
}

func (_c *IEC2MdsSdkClient_GetRegion_Call) Return(_a0 *imds.GetRegionOutput, _a1 error) *IEC2MdsSdkClient_GetRegion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2MdsSdkClient_GetRegion_Call) RunAndReturn(run func(context.Context, *imds.GetRegionInput, ...func(*imds.Options)) (*imds.GetRegionOutput, error)) *IEC2MdsSdkClient_GetRegion_Call {
	_c.Call.Return(run)
	return _c
}

// NewIEC2MdsSdkClient creates a new instance of IEC2MdsSdkClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEC2MdsSdkClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEC2MdsSdkClient {
	mock := &IEC2MdsSdkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
