// Code generated by mockery v2.50.2. DO NOT EDIT.

package anonauth

import mock "github.com/stretchr/testify/mock"

// MockIClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

type MockIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IClient) EXPECT() *MockIClient_Expecter {
	return &MockIClient_Expecter{mock: &_m.Mock}
}

// RegisterManagedInstance provides a mock function with given fields: activationCode, activationID, publicKey, publicKeyType, fingerprint
func (_m *IClient) RegisterManagedInstance(activationCode string, activationID string, publicKey string, publicKeyType string, fingerprint string) (string, error) {
	ret := _m.Called(activationCode, activationID, publicKey, publicKeyType, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for RegisterManagedInstance")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) (string, error)); ok {
		return rf(activationCode, activationID, publicKey, publicKeyType, fingerprint)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) string); ok {
		r0 = rf(activationCode, activationID, publicKey, publicKeyType, fingerprint)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(activationCode, activationID, publicKey, publicKeyType, fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIClient_RegisterManagedInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterManagedInstance'
type MockIClient_RegisterManagedInstance_Call struct {
	*mock.Call
}

// RegisterManagedInstance is a helper method to define mock.On call
//   - activationCode string
//   - activationID string
//   - publicKey string
//   - publicKeyType string
//   - fingerprint string
func (_e *MockIClient_Expecter) RegisterManagedInstance(activationCode interface{}, activationID interface{}, publicKey interface{}, publicKeyType interface{}, fingerprint interface{}) *MockIClient_RegisterManagedInstance_Call {
	return &MockIClient_RegisterManagedInstance_Call{Call: _e.mock.On("RegisterManagedInstance", activationCode, activationID, publicKey, publicKeyType, fingerprint)}
}

func (_c *MockIClient_RegisterManagedInstance_Call) Run(run func(activationCode string, activationID string, publicKey string, publicKeyType string, fingerprint string)) *MockIClient_RegisterManagedInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockIClient_RegisterManagedInstance_Call) Return(_a0 string, _a1 error) *MockIClient_RegisterManagedInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIClient_RegisterManagedInstance_Call) RunAndReturn(run func(string, string, string, string, string) (string, error)) *MockIClient_RegisterManagedInstance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIClient creates a new instance of MockIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
