// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	aws "github.com/aws/aws-sdk-go-v2/aws"

	mock "github.com/stretchr/testify/mock"
)

// IEC2Identity is an autogenerated mock type for the IEC2Identity type
type IEC2Identity struct {
	mock.Mock
}

type IEC2Identity_Expecter struct {
	mock *mock.Mock
}

func (_m *IEC2Identity) EXPECT() *IEC2Identity_Expecter {
	return &IEC2Identity_Expecter{mock: &_m.Mock}
}

// AvailabilityZone provides a mock function with no fields
func (_m *IEC2Identity) AvailabilityZone() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZone")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2Identity_AvailabilityZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZone'
type IEC2Identity_AvailabilityZone_Call struct {
	*mock.Call
}

// AvailabilityZone is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) AvailabilityZone() *IEC2Identity_AvailabilityZone_Call {
	return &IEC2Identity_AvailabilityZone_Call{Call: _e.mock.On("AvailabilityZone")}
}

func (_c *IEC2Identity_AvailabilityZone_Call) Run(run func()) *IEC2Identity_AvailabilityZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_AvailabilityZone_Call) Return(_a0 string, _a1 error) *IEC2Identity_AvailabilityZone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2Identity_AvailabilityZone_Call) RunAndReturn(run func() (string, error)) *IEC2Identity_AvailabilityZone_Call {
	_c.Call.Return(run)
	return _c
}

// AvailabilityZoneId provides a mock function with no fields
func (_m *IEC2Identity) AvailabilityZoneId() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZoneId")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2Identity_AvailabilityZoneId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZoneId'
type IEC2Identity_AvailabilityZoneId_Call struct {
	*mock.Call
}

// AvailabilityZoneId is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) AvailabilityZoneId() *IEC2Identity_AvailabilityZoneId_Call {
	return &IEC2Identity_AvailabilityZoneId_Call{Call: _e.mock.On("AvailabilityZoneId")}
}

func (_c *IEC2Identity_AvailabilityZoneId_Call) Run(run func()) *IEC2Identity_AvailabilityZoneId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_AvailabilityZoneId_Call) Return(_a0 string, _a1 error) *IEC2Identity_AvailabilityZoneId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2Identity_AvailabilityZoneId_Call) RunAndReturn(run func() (string, error)) *IEC2Identity_AvailabilityZoneId_Call {
	_c.Call.Return(run)
	return _c
}

// CredentialsProvider provides a mock function with no fields
func (_m *IEC2Identity) CredentialsProvider() aws.CredentialsProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialsProvider")
	}

	var r0 aws.CredentialsProvider
	if rf, ok := ret.Get(0).(func() aws.CredentialsProvider); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(aws.CredentialsProvider)
	}

	return r0
}

// IEC2Identity_CredentialsProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialsProvider'
type IEC2Identity_CredentialsProvider_Call struct {
	*mock.Call
}

// CredentialsProvider is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) CredentialsProvider() *IEC2Identity_CredentialsProvider_Call {
	return &IEC2Identity_CredentialsProvider_Call{Call: _e.mock.On("CredentialsProvider")}
}

func (_c *IEC2Identity_CredentialsProvider_Call) Run(run func()) *IEC2Identity_CredentialsProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_CredentialsProvider_Call) Return(_a0 aws.CredentialsProvider) *IEC2Identity_CredentialsProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2Identity_CredentialsProvider_Call) RunAndReturn(run func() aws.CredentialsProvider) *IEC2Identity_CredentialsProvider_Call {
	_c.Call.Return(run)
	return _c
}

// IdentityType provides a mock function with no fields
func (_m *IEC2Identity) IdentityType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdentityType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IEC2Identity_IdentityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentityType'
type IEC2Identity_IdentityType_Call struct {
	*mock.Call
}

// IdentityType is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) IdentityType() *IEC2Identity_IdentityType_Call {
	return &IEC2Identity_IdentityType_Call{Call: _e.mock.On("IdentityType")}
}

func (_c *IEC2Identity_IdentityType_Call) Run(run func()) *IEC2Identity_IdentityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_IdentityType_Call) Return(_a0 string) *IEC2Identity_IdentityType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2Identity_IdentityType_Call) RunAndReturn(run func() string) *IEC2Identity_IdentityType_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceID provides a mock function with no fields
func (_m *IEC2Identity) InstanceID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstanceID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2Identity_InstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceID'
type IEC2Identity_InstanceID_Call struct {
	*mock.Call
}

// InstanceID is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) InstanceID() *IEC2Identity_InstanceID_Call {
	return &IEC2Identity_InstanceID_Call{Call: _e.mock.On("InstanceID")}
}

func (_c *IEC2Identity_InstanceID_Call) Run(run func()) *IEC2Identity_InstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_InstanceID_Call) Return(_a0 string, _a1 error) *IEC2Identity_InstanceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2Identity_InstanceID_Call) RunAndReturn(run func() (string, error)) *IEC2Identity_InstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceType provides a mock function with no fields
func (_m *IEC2Identity) InstanceType() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstanceType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2Identity_InstanceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceType'
type IEC2Identity_InstanceType_Call struct {
	*mock.Call
}

// InstanceType is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) InstanceType() *IEC2Identity_InstanceType_Call {
	return &IEC2Identity_InstanceType_Call{Call: _e.mock.On("InstanceType")}
}

func (_c *IEC2Identity_InstanceType_Call) Run(run func()) *IEC2Identity_InstanceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_InstanceType_Call) Return(_a0 string, _a1 error) *IEC2Identity_InstanceType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2Identity_InstanceType_Call) RunAndReturn(run func() (string, error)) *IEC2Identity_InstanceType_Call {
	_c.Call.Return(run)
	return _c
}

// IsIdentityEnvironment provides a mock function with no fields
func (_m *IEC2Identity) IsIdentityEnvironment() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsIdentityEnvironment")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IEC2Identity_IsIdentityEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIdentityEnvironment'
type IEC2Identity_IsIdentityEnvironment_Call struct {
	*mock.Call
}

// IsIdentityEnvironment is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) IsIdentityEnvironment() *IEC2Identity_IsIdentityEnvironment_Call {
	return &IEC2Identity_IsIdentityEnvironment_Call{Call: _e.mock.On("IsIdentityEnvironment")}
}

func (_c *IEC2Identity_IsIdentityEnvironment_Call) Run(run func()) *IEC2Identity_IsIdentityEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_IsIdentityEnvironment_Call) Return(_a0 bool) *IEC2Identity_IsIdentityEnvironment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2Identity_IsIdentityEnvironment_Call) RunAndReturn(run func() bool) *IEC2Identity_IsIdentityEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// Region provides a mock function with no fields
func (_m *IEC2Identity) Region() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Region")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2Identity_Region_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Region'
type IEC2Identity_Region_Call struct {
	*mock.Call
}

// Region is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) Region() *IEC2Identity_Region_Call {
	return &IEC2Identity_Region_Call{Call: _e.mock.On("Region")}
}

func (_c *IEC2Identity_Region_Call) Run(run func()) *IEC2Identity_Region_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_Region_Call) Return(_a0 string, _a1 error) *IEC2Identity_Region_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2Identity_Region_Call) RunAndReturn(run func() (string, error)) *IEC2Identity_Region_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with no fields
func (_m *IEC2Identity) Register() {
	_m.Called()
}

// IEC2Identity_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type IEC2Identity_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
func (_e *IEC2Identity_Expecter) Register() *IEC2Identity_Register_Call {
	return &IEC2Identity_Register_Call{Call: _e.mock.On("Register")}
}

func (_c *IEC2Identity_Register_Call) Run(run func()) *IEC2Identity_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2Identity_Register_Call) Return() *IEC2Identity_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *IEC2Identity_Register_Call) RunAndReturn(run func()) *IEC2Identity_Register_Call {
	_c.Run(run)
	return _c
}

// NewIEC2Identity creates a new instance of IEC2Identity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEC2Identity(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEC2Identity {
	mock := &IEC2Identity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
