// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	aws "github.com/aws/aws-sdk-go-v2/aws"

	ec2roleprovider "github.com/aws/amazon-ssm-agent/common/identity/credentialproviders/ec2roleprovider"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IEC2RoleProvider is an autogenerated mock type for the IEC2RoleProvider type
type IEC2RoleProvider struct {
	mock.Mock
}

type IEC2RoleProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *IEC2RoleProvider) EXPECT() *IEC2RoleProvider_Expecter {
	return &IEC2RoleProvider_Expecter{mock: &_m.Mock}
}

// CredentialSource provides a mock function with no fields
func (_m *IEC2RoleProvider) CredentialSource() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialSource")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IEC2RoleProvider_CredentialSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialSource'
type IEC2RoleProvider_CredentialSource_Call struct {
	*mock.Call
}

// CredentialSource is a helper method to define mock.On call
func (_e *IEC2RoleProvider_Expecter) CredentialSource() *IEC2RoleProvider_CredentialSource_Call {
	return &IEC2RoleProvider_CredentialSource_Call{Call: _e.mock.On("CredentialSource")}
}

func (_c *IEC2RoleProvider_CredentialSource_Call) Run(run func()) *IEC2RoleProvider_CredentialSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2RoleProvider_CredentialSource_Call) Return(_a0 string) *IEC2RoleProvider_CredentialSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2RoleProvider_CredentialSource_Call) RunAndReturn(run func() string) *IEC2RoleProvider_CredentialSource_Call {
	_c.Call.Return(run)
	return _c
}

// GetInnerProvider provides a mock function with no fields
func (_m *IEC2RoleProvider) GetInnerProvider() ec2roleprovider.IInnerProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInnerProvider")
	}

	var r0 ec2roleprovider.IInnerProvider
	if rf, ok := ret.Get(0).(func() ec2roleprovider.IInnerProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ec2roleprovider.IInnerProvider)
		}
	}

	return r0
}

// IEC2RoleProvider_GetInnerProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInnerProvider'
type IEC2RoleProvider_GetInnerProvider_Call struct {
	*mock.Call
}

// GetInnerProvider is a helper method to define mock.On call
func (_e *IEC2RoleProvider_Expecter) GetInnerProvider() *IEC2RoleProvider_GetInnerProvider_Call {
	return &IEC2RoleProvider_GetInnerProvider_Call{Call: _e.mock.On("GetInnerProvider")}
}

func (_c *IEC2RoleProvider_GetInnerProvider_Call) Run(run func()) *IEC2RoleProvider_GetInnerProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2RoleProvider_GetInnerProvider_Call) Return(_a0 ec2roleprovider.IInnerProvider) *IEC2RoleProvider_GetInnerProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2RoleProvider_GetInnerProvider_Call) RunAndReturn(run func() ec2roleprovider.IInnerProvider) *IEC2RoleProvider_GetInnerProvider_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteExpiresAt provides a mock function with no fields
func (_m *IEC2RoleProvider) RemoteExpiresAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteExpiresAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// IEC2RoleProvider_RemoteExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteExpiresAt'
type IEC2RoleProvider_RemoteExpiresAt_Call struct {
	*mock.Call
}

// RemoteExpiresAt is a helper method to define mock.On call
func (_e *IEC2RoleProvider_Expecter) RemoteExpiresAt() *IEC2RoleProvider_RemoteExpiresAt_Call {
	return &IEC2RoleProvider_RemoteExpiresAt_Call{Call: _e.mock.On("RemoteExpiresAt")}
}

func (_c *IEC2RoleProvider_RemoteExpiresAt_Call) Run(run func()) *IEC2RoleProvider_RemoteExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2RoleProvider_RemoteExpiresAt_Call) Return(_a0 time.Time) *IEC2RoleProvider_RemoteExpiresAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2RoleProvider_RemoteExpiresAt_Call) RunAndReturn(run func() time.Time) *IEC2RoleProvider_RemoteExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteRetrieve provides a mock function with given fields: ctx
func (_m *IEC2RoleProvider) RemoteRetrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RemoteRetrieve")
	}

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2RoleProvider_RemoteRetrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteRetrieve'
type IEC2RoleProvider_RemoteRetrieve_Call struct {
	*mock.Call
}

// RemoteRetrieve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IEC2RoleProvider_Expecter) RemoteRetrieve(ctx interface{}) *IEC2RoleProvider_RemoteRetrieve_Call {
	return &IEC2RoleProvider_RemoteRetrieve_Call{Call: _e.mock.On("RemoteRetrieve", ctx)}
}

func (_c *IEC2RoleProvider_RemoteRetrieve_Call) Run(run func(ctx context.Context)) *IEC2RoleProvider_RemoteRetrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IEC2RoleProvider_RemoteRetrieve_Call) Return(_a0 aws.Credentials, _a1 error) *IEC2RoleProvider_RemoteRetrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2RoleProvider_RemoteRetrieve_Call) RunAndReturn(run func(context.Context) (aws.Credentials, error)) *IEC2RoleProvider_RemoteRetrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ctx
func (_m *IEC2RoleProvider) Retrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IEC2RoleProvider_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type IEC2RoleProvider_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IEC2RoleProvider_Expecter) Retrieve(ctx interface{}) *IEC2RoleProvider_Retrieve_Call {
	return &IEC2RoleProvider_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx)}
}

func (_c *IEC2RoleProvider_Retrieve_Call) Run(run func(ctx context.Context)) *IEC2RoleProvider_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IEC2RoleProvider_Retrieve_Call) Return(_a0 aws.Credentials, _a1 error) *IEC2RoleProvider_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IEC2RoleProvider_Retrieve_Call) RunAndReturn(run func(context.Context) (aws.Credentials, error)) *IEC2RoleProvider_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// ShareFile provides a mock function with no fields
func (_m *IEC2RoleProvider) ShareFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShareFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IEC2RoleProvider_ShareFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareFile'
type IEC2RoleProvider_ShareFile_Call struct {
	*mock.Call
}

// ShareFile is a helper method to define mock.On call
func (_e *IEC2RoleProvider_Expecter) ShareFile() *IEC2RoleProvider_ShareFile_Call {
	return &IEC2RoleProvider_ShareFile_Call{Call: _e.mock.On("ShareFile")}
}

func (_c *IEC2RoleProvider_ShareFile_Call) Run(run func()) *IEC2RoleProvider_ShareFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2RoleProvider_ShareFile_Call) Return(_a0 string) *IEC2RoleProvider_ShareFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2RoleProvider_ShareFile_Call) RunAndReturn(run func() string) *IEC2RoleProvider_ShareFile_Call {
	_c.Call.Return(run)
	return _c
}

// ShareProfile provides a mock function with no fields
func (_m *IEC2RoleProvider) ShareProfile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShareProfile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IEC2RoleProvider_ShareProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareProfile'
type IEC2RoleProvider_ShareProfile_Call struct {
	*mock.Call
}

// ShareProfile is a helper method to define mock.On call
func (_e *IEC2RoleProvider_Expecter) ShareProfile() *IEC2RoleProvider_ShareProfile_Call {
	return &IEC2RoleProvider_ShareProfile_Call{Call: _e.mock.On("ShareProfile")}
}

func (_c *IEC2RoleProvider_ShareProfile_Call) Run(run func()) *IEC2RoleProvider_ShareProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2RoleProvider_ShareProfile_Call) Return(_a0 string) *IEC2RoleProvider_ShareProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2RoleProvider_ShareProfile_Call) RunAndReturn(run func() string) *IEC2RoleProvider_ShareProfile_Call {
	_c.Call.Return(run)
	return _c
}

// SharesCredentials provides a mock function with no fields
func (_m *IEC2RoleProvider) SharesCredentials() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SharesCredentials")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IEC2RoleProvider_SharesCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharesCredentials'
type IEC2RoleProvider_SharesCredentials_Call struct {
	*mock.Call
}

// SharesCredentials is a helper method to define mock.On call
func (_e *IEC2RoleProvider_Expecter) SharesCredentials() *IEC2RoleProvider_SharesCredentials_Call {
	return &IEC2RoleProvider_SharesCredentials_Call{Call: _e.mock.On("SharesCredentials")}
}

func (_c *IEC2RoleProvider_SharesCredentials_Call) Run(run func()) *IEC2RoleProvider_SharesCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IEC2RoleProvider_SharesCredentials_Call) Return(_a0 bool) *IEC2RoleProvider_SharesCredentials_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IEC2RoleProvider_SharesCredentials_Call) RunAndReturn(run func() bool) *IEC2RoleProvider_SharesCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// NewIEC2RoleProvider creates a new instance of IEC2RoleProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIEC2RoleProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IEC2RoleProvider {
	mock := &IEC2RoleProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
