// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	aws "github.com/aws/aws-sdk-go-v2/aws"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IInnerProvider is an autogenerated mock type for the IInnerProvider type
type IInnerProvider struct {
	mock.Mock
}

type IInnerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *IInnerProvider) EXPECT() *IInnerProvider_Expecter {
	return &IInnerProvider_Expecter{mock: &_m.Mock}
}

// ExpiresAt provides a mock function with no fields
func (_m *IInnerProvider) ExpiresAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpiresAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// IInnerProvider_ExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpiresAt'
type IInnerProvider_ExpiresAt_Call struct {
	*mock.Call
}

// ExpiresAt is a helper method to define mock.On call
func (_e *IInnerProvider_Expecter) ExpiresAt() *IInnerProvider_ExpiresAt_Call {
	return &IInnerProvider_ExpiresAt_Call{Call: _e.mock.On("ExpiresAt")}
}

func (_c *IInnerProvider_ExpiresAt_Call) Run(run func()) *IInnerProvider_ExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IInnerProvider_ExpiresAt_Call) Return(_a0 time.Time) *IInnerProvider_ExpiresAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IInnerProvider_ExpiresAt_Call) RunAndReturn(run func() time.Time) *IInnerProvider_ExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// IsExpired provides a mock function with no fields
func (_m *IInnerProvider) IsExpired() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsExpired")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IInnerProvider_IsExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExpired'
type IInnerProvider_IsExpired_Call struct {
	*mock.Call
}

// IsExpired is a helper method to define mock.On call
func (_e *IInnerProvider_Expecter) IsExpired() *IInnerProvider_IsExpired_Call {
	return &IInnerProvider_IsExpired_Call{Call: _e.mock.On("IsExpired")}
}

func (_c *IInnerProvider_IsExpired_Call) Run(run func()) *IInnerProvider_IsExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IInnerProvider_IsExpired_Call) Return(_a0 bool) *IInnerProvider_IsExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IInnerProvider_IsExpired_Call) RunAndReturn(run func() bool) *IInnerProvider_IsExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ctx
func (_m *IInnerProvider) Retrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IInnerProvider_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type IInnerProvider_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IInnerProvider_Expecter) Retrieve(ctx interface{}) *IInnerProvider_Retrieve_Call {
	return &IInnerProvider_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx)}
}

func (_c *IInnerProvider_Retrieve_Call) Run(run func(ctx context.Context)) *IInnerProvider_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IInnerProvider_Retrieve_Call) Return(_a0 aws.Credentials, _a1 error) *IInnerProvider_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IInnerProvider_Retrieve_Call) RunAndReturn(run func(context.Context) (aws.Credentials, error)) *IInnerProvider_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// NewIInnerProvider creates a new instance of IInnerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInnerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInnerProvider {
	mock := &IInnerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
