// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	aws "github.com/aws/aws-sdk-go-v2/aws"

	mock "github.com/stretchr/testify/mock"
)

// IAgentIdentity is an autogenerated mock type for the IAgentIdentity type
type IAgentIdentity struct {
	mock.Mock
}

type IAgentIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *IAgentIdentity) EXPECT() *IAgentIdentity_Expecter {
	return &IAgentIdentity_Expecter{mock: &_m.Mock}
}

// AvailabilityZone provides a mock function with no fields
func (_m *IAgentIdentity) AvailabilityZone() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZone")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentity_AvailabilityZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZone'
type IAgentIdentity_AvailabilityZone_Call struct {
	*mock.Call
}

// AvailabilityZone is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) AvailabilityZone() *IAgentIdentity_AvailabilityZone_Call {
	return &IAgentIdentity_AvailabilityZone_Call{Call: _e.mock.On("AvailabilityZone")}
}

func (_c *IAgentIdentity_AvailabilityZone_Call) Run(run func()) *IAgentIdentity_AvailabilityZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_AvailabilityZone_Call) Return(_a0 string, _a1 error) *IAgentIdentity_AvailabilityZone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentity_AvailabilityZone_Call) RunAndReturn(run func() (string, error)) *IAgentIdentity_AvailabilityZone_Call {
	_c.Call.Return(run)
	return _c
}

// AvailabilityZoneId provides a mock function with no fields
func (_m *IAgentIdentity) AvailabilityZoneId() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZoneId")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentity_AvailabilityZoneId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZoneId'
type IAgentIdentity_AvailabilityZoneId_Call struct {
	*mock.Call
}

// AvailabilityZoneId is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) AvailabilityZoneId() *IAgentIdentity_AvailabilityZoneId_Call {
	return &IAgentIdentity_AvailabilityZoneId_Call{Call: _e.mock.On("AvailabilityZoneId")}
}

func (_c *IAgentIdentity_AvailabilityZoneId_Call) Run(run func()) *IAgentIdentity_AvailabilityZoneId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_AvailabilityZoneId_Call) Return(_a0 string, _a1 error) *IAgentIdentity_AvailabilityZoneId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentity_AvailabilityZoneId_Call) RunAndReturn(run func() (string, error)) *IAgentIdentity_AvailabilityZoneId_Call {
	_c.Call.Return(run)
	return _c
}

// CredentialsProvider provides a mock function with no fields
func (_m *IAgentIdentity) CredentialsProvider() aws.CredentialsProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialsProvider")
	}

	var r0 aws.CredentialsProvider
	if rf, ok := ret.Get(0).(func() aws.CredentialsProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aws.CredentialsProvider)
		}
	}

	return r0
}

// IAgentIdentity_CredentialsProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialsProvider'
type IAgentIdentity_CredentialsProvider_Call struct {
	*mock.Call
}

// CredentialsProvider is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) CredentialsProvider() *IAgentIdentity_CredentialsProvider_Call {
	return &IAgentIdentity_CredentialsProvider_Call{Call: _e.mock.On("CredentialsProvider")}
}

func (_c *IAgentIdentity_CredentialsProvider_Call) Run(run func()) *IAgentIdentity_CredentialsProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_CredentialsProvider_Call) Return(_a0 aws.CredentialsProvider) *IAgentIdentity_CredentialsProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAgentIdentity_CredentialsProvider_Call) RunAndReturn(run func() aws.CredentialsProvider) *IAgentIdentity_CredentialsProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceEndpoint provides a mock function with given fields: _a0
func (_m *IAgentIdentity) GetServiceEndpoint(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IAgentIdentity_GetServiceEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceEndpoint'
type IAgentIdentity_GetServiceEndpoint_Call struct {
	*mock.Call
}

// GetServiceEndpoint is a helper method to define mock.On call
//   - _a0 string
func (_e *IAgentIdentity_Expecter) GetServiceEndpoint(_a0 interface{}) *IAgentIdentity_GetServiceEndpoint_Call {
	return &IAgentIdentity_GetServiceEndpoint_Call{Call: _e.mock.On("GetServiceEndpoint", _a0)}
}

func (_c *IAgentIdentity_GetServiceEndpoint_Call) Run(run func(_a0 string)) *IAgentIdentity_GetServiceEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IAgentIdentity_GetServiceEndpoint_Call) Return(_a0 string) *IAgentIdentity_GetServiceEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAgentIdentity_GetServiceEndpoint_Call) RunAndReturn(run func(string) string) *IAgentIdentity_GetServiceEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// IdentityType provides a mock function with no fields
func (_m *IAgentIdentity) IdentityType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdentityType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IAgentIdentity_IdentityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentityType'
type IAgentIdentity_IdentityType_Call struct {
	*mock.Call
}

// IdentityType is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) IdentityType() *IAgentIdentity_IdentityType_Call {
	return &IAgentIdentity_IdentityType_Call{Call: _e.mock.On("IdentityType")}
}

func (_c *IAgentIdentity_IdentityType_Call) Run(run func()) *IAgentIdentity_IdentityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_IdentityType_Call) Return(_a0 string) *IAgentIdentity_IdentityType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAgentIdentity_IdentityType_Call) RunAndReturn(run func() string) *IAgentIdentity_IdentityType_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceID provides a mock function with no fields
func (_m *IAgentIdentity) InstanceID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstanceID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentity_InstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceID'
type IAgentIdentity_InstanceID_Call struct {
	*mock.Call
}

// InstanceID is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) InstanceID() *IAgentIdentity_InstanceID_Call {
	return &IAgentIdentity_InstanceID_Call{Call: _e.mock.On("InstanceID")}
}

func (_c *IAgentIdentity_InstanceID_Call) Run(run func()) *IAgentIdentity_InstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_InstanceID_Call) Return(_a0 string, _a1 error) *IAgentIdentity_InstanceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentity_InstanceID_Call) RunAndReturn(run func() (string, error)) *IAgentIdentity_InstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceType provides a mock function with no fields
func (_m *IAgentIdentity) InstanceType() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstanceType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentity_InstanceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceType'
type IAgentIdentity_InstanceType_Call struct {
	*mock.Call
}

// InstanceType is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) InstanceType() *IAgentIdentity_InstanceType_Call {
	return &IAgentIdentity_InstanceType_Call{Call: _e.mock.On("InstanceType")}
}

func (_c *IAgentIdentity_InstanceType_Call) Run(run func()) *IAgentIdentity_InstanceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_InstanceType_Call) Return(_a0 string, _a1 error) *IAgentIdentity_InstanceType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentity_InstanceType_Call) RunAndReturn(run func() (string, error)) *IAgentIdentity_InstanceType_Call {
	_c.Call.Return(run)
	return _c
}

// Region provides a mock function with no fields
func (_m *IAgentIdentity) Region() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Region")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentity_Region_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Region'
type IAgentIdentity_Region_Call struct {
	*mock.Call
}

// Region is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) Region() *IAgentIdentity_Region_Call {
	return &IAgentIdentity_Region_Call{Call: _e.mock.On("Region")}
}

func (_c *IAgentIdentity_Region_Call) Run(run func()) *IAgentIdentity_Region_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_Region_Call) Return(_a0 string, _a1 error) *IAgentIdentity_Region_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentity_Region_Call) RunAndReturn(run func() (string, error)) *IAgentIdentity_Region_Call {
	_c.Call.Return(run)
	return _c
}

// ShortInstanceID provides a mock function with no fields
func (_m *IAgentIdentity) ShortInstanceID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShortInstanceID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentity_ShortInstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortInstanceID'
type IAgentIdentity_ShortInstanceID_Call struct {
	*mock.Call
}

// ShortInstanceID is a helper method to define mock.On call
func (_e *IAgentIdentity_Expecter) ShortInstanceID() *IAgentIdentity_ShortInstanceID_Call {
	return &IAgentIdentity_ShortInstanceID_Call{Call: _e.mock.On("ShortInstanceID")}
}

func (_c *IAgentIdentity_ShortInstanceID_Call) Run(run func()) *IAgentIdentity_ShortInstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentity_ShortInstanceID_Call) Return(_a0 string, _a1 error) *IAgentIdentity_ShortInstanceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentity_ShortInstanceID_Call) RunAndReturn(run func() (string, error)) *IAgentIdentity_ShortInstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAgentIdentity creates a new instance of IAgentIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAgentIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAgentIdentity {
	mock := &IAgentIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
