// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	aws "github.com/aws/aws-sdk-go-v2/aws"

	mock "github.com/stretchr/testify/mock"
)

// IAgentIdentityInner is an autogenerated mock type for the IAgentIdentityInner type
type IAgentIdentityInner struct {
	mock.Mock
}

type IAgentIdentityInner_Expecter struct {
	mock *mock.Mock
}

func (_m *IAgentIdentityInner) EXPECT() *IAgentIdentityInner_Expecter {
	return &IAgentIdentityInner_Expecter{mock: &_m.Mock}
}

// AvailabilityZone provides a mock function with no fields
func (_m *IAgentIdentityInner) AvailabilityZone() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZone")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentityInner_AvailabilityZone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZone'
type IAgentIdentityInner_AvailabilityZone_Call struct {
	*mock.Call
}

// AvailabilityZone is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) AvailabilityZone() *IAgentIdentityInner_AvailabilityZone_Call {
	return &IAgentIdentityInner_AvailabilityZone_Call{Call: _e.mock.On("AvailabilityZone")}
}

func (_c *IAgentIdentityInner_AvailabilityZone_Call) Run(run func()) *IAgentIdentityInner_AvailabilityZone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_AvailabilityZone_Call) Return(_a0 string, _a1 error) *IAgentIdentityInner_AvailabilityZone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentityInner_AvailabilityZone_Call) RunAndReturn(run func() (string, error)) *IAgentIdentityInner_AvailabilityZone_Call {
	_c.Call.Return(run)
	return _c
}

// AvailabilityZoneId provides a mock function with no fields
func (_m *IAgentIdentityInner) AvailabilityZoneId() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AvailabilityZoneId")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentityInner_AvailabilityZoneId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AvailabilityZoneId'
type IAgentIdentityInner_AvailabilityZoneId_Call struct {
	*mock.Call
}

// AvailabilityZoneId is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) AvailabilityZoneId() *IAgentIdentityInner_AvailabilityZoneId_Call {
	return &IAgentIdentityInner_AvailabilityZoneId_Call{Call: _e.mock.On("AvailabilityZoneId")}
}

func (_c *IAgentIdentityInner_AvailabilityZoneId_Call) Run(run func()) *IAgentIdentityInner_AvailabilityZoneId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_AvailabilityZoneId_Call) Return(_a0 string, _a1 error) *IAgentIdentityInner_AvailabilityZoneId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentityInner_AvailabilityZoneId_Call) RunAndReturn(run func() (string, error)) *IAgentIdentityInner_AvailabilityZoneId_Call {
	_c.Call.Return(run)
	return _c
}

// CredentialsProvider provides a mock function with no fields
func (_m *IAgentIdentityInner) CredentialsProvider() aws.CredentialsProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialsProvider")
	}

	var r0 aws.CredentialsProvider
	if rf, ok := ret.Get(0).(func() aws.CredentialsProvider); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(aws.CredentialsProvider)
	}

	return r0
}

// IAgentIdentityInner_CredentialsProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialsProvider'
type IAgentIdentityInner_CredentialsProvider_Call struct {
	*mock.Call
}

// CredentialsProvider is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) CredentialsProvider() *IAgentIdentityInner_CredentialsProvider_Call {
	return &IAgentIdentityInner_CredentialsProvider_Call{Call: _e.mock.On("CredentialsProvider")}
}

func (_c *IAgentIdentityInner_CredentialsProvider_Call) Run(run func()) *IAgentIdentityInner_CredentialsProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_CredentialsProvider_Call) Return(_a0 aws.CredentialsProvider) *IAgentIdentityInner_CredentialsProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAgentIdentityInner_CredentialsProvider_Call) RunAndReturn(run func() aws.CredentialsProvider) *IAgentIdentityInner_CredentialsProvider_Call {
	_c.Call.Return(run)
	return _c
}

// IdentityType provides a mock function with no fields
func (_m *IAgentIdentityInner) IdentityType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdentityType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IAgentIdentityInner_IdentityType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentityType'
type IAgentIdentityInner_IdentityType_Call struct {
	*mock.Call
}

// IdentityType is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) IdentityType() *IAgentIdentityInner_IdentityType_Call {
	return &IAgentIdentityInner_IdentityType_Call{Call: _e.mock.On("IdentityType")}
}

func (_c *IAgentIdentityInner_IdentityType_Call) Run(run func()) *IAgentIdentityInner_IdentityType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_IdentityType_Call) Return(_a0 string) *IAgentIdentityInner_IdentityType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAgentIdentityInner_IdentityType_Call) RunAndReturn(run func() string) *IAgentIdentityInner_IdentityType_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceID provides a mock function with no fields
func (_m *IAgentIdentityInner) InstanceID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstanceID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentityInner_InstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceID'
type IAgentIdentityInner_InstanceID_Call struct {
	*mock.Call
}

// InstanceID is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) InstanceID() *IAgentIdentityInner_InstanceID_Call {
	return &IAgentIdentityInner_InstanceID_Call{Call: _e.mock.On("InstanceID")}
}

func (_c *IAgentIdentityInner_InstanceID_Call) Run(run func()) *IAgentIdentityInner_InstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_InstanceID_Call) Return(_a0 string, _a1 error) *IAgentIdentityInner_InstanceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentityInner_InstanceID_Call) RunAndReturn(run func() (string, error)) *IAgentIdentityInner_InstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// InstanceType provides a mock function with no fields
func (_m *IAgentIdentityInner) InstanceType() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InstanceType")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentityInner_InstanceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstanceType'
type IAgentIdentityInner_InstanceType_Call struct {
	*mock.Call
}

// InstanceType is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) InstanceType() *IAgentIdentityInner_InstanceType_Call {
	return &IAgentIdentityInner_InstanceType_Call{Call: _e.mock.On("InstanceType")}
}

func (_c *IAgentIdentityInner_InstanceType_Call) Run(run func()) *IAgentIdentityInner_InstanceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_InstanceType_Call) Return(_a0 string, _a1 error) *IAgentIdentityInner_InstanceType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentityInner_InstanceType_Call) RunAndReturn(run func() (string, error)) *IAgentIdentityInner_InstanceType_Call {
	_c.Call.Return(run)
	return _c
}

// IsIdentityEnvironment provides a mock function with no fields
func (_m *IAgentIdentityInner) IsIdentityEnvironment() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsIdentityEnvironment")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IAgentIdentityInner_IsIdentityEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIdentityEnvironment'
type IAgentIdentityInner_IsIdentityEnvironment_Call struct {
	*mock.Call
}

// IsIdentityEnvironment is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) IsIdentityEnvironment() *IAgentIdentityInner_IsIdentityEnvironment_Call {
	return &IAgentIdentityInner_IsIdentityEnvironment_Call{Call: _e.mock.On("IsIdentityEnvironment")}
}

func (_c *IAgentIdentityInner_IsIdentityEnvironment_Call) Run(run func()) *IAgentIdentityInner_IsIdentityEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_IsIdentityEnvironment_Call) Return(_a0 bool) *IAgentIdentityInner_IsIdentityEnvironment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAgentIdentityInner_IsIdentityEnvironment_Call) RunAndReturn(run func() bool) *IAgentIdentityInner_IsIdentityEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// Region provides a mock function with no fields
func (_m *IAgentIdentityInner) Region() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Region")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IAgentIdentityInner_Region_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Region'
type IAgentIdentityInner_Region_Call struct {
	*mock.Call
}

// Region is a helper method to define mock.On call
func (_e *IAgentIdentityInner_Expecter) Region() *IAgentIdentityInner_Region_Call {
	return &IAgentIdentityInner_Region_Call{Call: _e.mock.On("Region")}
}

func (_c *IAgentIdentityInner_Region_Call) Run(run func()) *IAgentIdentityInner_Region_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IAgentIdentityInner_Region_Call) Return(_a0 string, _a1 error) *IAgentIdentityInner_Region_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IAgentIdentityInner_Region_Call) RunAndReturn(run func() (string, error)) *IAgentIdentityInner_Region_Call {
	_c.Call.Return(run)
	return _c
}

// NewIAgentIdentityInner creates a new instance of IAgentIdentityInner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAgentIdentityInner(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAgentIdentityInner {
	mock := &IAgentIdentityInner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
