// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	credentialproviders "github.com/aws/amazon-ssm-agent/common/identity/credentialproviders"

	mock "github.com/stretchr/testify/mock"
)

// ICredentialRefresherAgentIdentity is an autogenerated mock type for the ICredentialRefresherAgentIdentity type
type ICredentialRefresherAgentIdentity struct {
	mock.Mock
}

type ICredentialRefresherAgentIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *ICredentialRefresherAgentIdentity) EXPECT() *ICredentialRefresherAgentIdentity_Expecter {
	return &ICredentialRefresherAgentIdentity_Expecter{mock: &_m.Mock}
}

// CredentialProvider provides a mock function with no fields
func (_m *ICredentialRefresherAgentIdentity) CredentialProvider() credentialproviders.IRemoteProvider {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialProvider")
	}

	var r0 credentialproviders.IRemoteProvider
	if rf, ok := ret.Get(0).(func() credentialproviders.IRemoteProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(credentialproviders.IRemoteProvider)
		}
	}

	return r0
}

// ICredentialRefresherAgentIdentity_CredentialProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialProvider'
type ICredentialRefresherAgentIdentity_CredentialProvider_Call struct {
	*mock.Call
}

// CredentialProvider is a helper method to define mock.On call
func (_e *ICredentialRefresherAgentIdentity_Expecter) CredentialProvider() *ICredentialRefresherAgentIdentity_CredentialProvider_Call {
	return &ICredentialRefresherAgentIdentity_CredentialProvider_Call{Call: _e.mock.On("CredentialProvider")}
}

func (_c *ICredentialRefresherAgentIdentity_CredentialProvider_Call) Run(run func()) *ICredentialRefresherAgentIdentity_CredentialProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ICredentialRefresherAgentIdentity_CredentialProvider_Call) Return(_a0 credentialproviders.IRemoteProvider) *ICredentialRefresherAgentIdentity_CredentialProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ICredentialRefresherAgentIdentity_CredentialProvider_Call) RunAndReturn(run func() credentialproviders.IRemoteProvider) *ICredentialRefresherAgentIdentity_CredentialProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewICredentialRefresherAgentIdentity creates a new instance of ICredentialRefresherAgentIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICredentialRefresherAgentIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICredentialRefresherAgentIdentity {
	mock := &ICredentialRefresherAgentIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
