// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	identity "github.com/aws/amazon-ssm-agent/common/identity"
	mock "github.com/stretchr/testify/mock"
)

// IInnerIdentityGetter is an autogenerated mock type for the IInnerIdentityGetter type
type IInnerIdentityGetter struct {
	mock.Mock
}

type IInnerIdentityGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *IInnerIdentityGetter) EXPECT() *IInnerIdentityGetter_Expecter {
	return &IInnerIdentityGetter_Expecter{mock: &_m.Mock}
}

// GetInner provides a mock function with no fields
func (_m *IInnerIdentityGetter) GetInner() identity.IAgentIdentityInner {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInner")
	}

	var r0 identity.IAgentIdentityInner
	if rf, ok := ret.Get(0).(func() identity.IAgentIdentityInner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(identity.IAgentIdentityInner)
		}
	}

	return r0
}

// IInnerIdentityGetter_GetInner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInner'
type IInnerIdentityGetter_GetInner_Call struct {
	*mock.Call
}

// GetInner is a helper method to define mock.On call
func (_e *IInnerIdentityGetter_Expecter) GetInner() *IInnerIdentityGetter_GetInner_Call {
	return &IInnerIdentityGetter_GetInner_Call{Call: _e.mock.On("GetInner")}
}

func (_c *IInnerIdentityGetter_GetInner_Call) Run(run func()) *IInnerIdentityGetter_GetInner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IInnerIdentityGetter_GetInner_Call) Return(_a0 identity.IAgentIdentityInner) *IInnerIdentityGetter_GetInner_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IInnerIdentityGetter_GetInner_Call) RunAndReturn(run func() identity.IAgentIdentityInner) *IInnerIdentityGetter_GetInner_Call {
	_c.Call.Return(run)
	return _c
}

// NewIInnerIdentityGetter creates a new instance of IInnerIdentityGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInnerIdentityGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInnerIdentityGetter {
	mock := &IInnerIdentityGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
