// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMetadataIdentity is an autogenerated mock type for the IMetadataIdentity type
type IMetadataIdentity struct {
	mock.Mock
}

type IMetadataIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *IMetadataIdentity) EXPECT() *IMetadataIdentity_Expecter {
	return &IMetadataIdentity_Expecter{mock: &_m.Mock}
}

// VpcPrimaryCIDRBlock provides a mock function with no fields
func (_m *IMetadataIdentity) VpcPrimaryCIDRBlock() (map[string][]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for VpcPrimaryCIDRBlock")
	}

	var r0 map[string][]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string][]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string][]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IMetadataIdentity_VpcPrimaryCIDRBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VpcPrimaryCIDRBlock'
type IMetadataIdentity_VpcPrimaryCIDRBlock_Call struct {
	*mock.Call
}

// VpcPrimaryCIDRBlock is a helper method to define mock.On call
func (_e *IMetadataIdentity_Expecter) VpcPrimaryCIDRBlock() *IMetadataIdentity_VpcPrimaryCIDRBlock_Call {
	return &IMetadataIdentity_VpcPrimaryCIDRBlock_Call{Call: _e.mock.On("VpcPrimaryCIDRBlock")}
}

func (_c *IMetadataIdentity_VpcPrimaryCIDRBlock_Call) Run(run func()) *IMetadataIdentity_VpcPrimaryCIDRBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IMetadataIdentity_VpcPrimaryCIDRBlock_Call) Return(_a0 map[string][]string, _a1 error) *IMetadataIdentity_VpcPrimaryCIDRBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IMetadataIdentity_VpcPrimaryCIDRBlock_Call) RunAndReturn(run func() (map[string][]string, error)) *IMetadataIdentity_VpcPrimaryCIDRBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewIMetadataIdentity creates a new instance of IMetadataIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMetadataIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMetadataIdentity {
	mock := &IMetadataIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
