// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Registrar is an autogenerated mock type for the Registrar type
type Registrar struct {
	mock.Mock
}

type Registrar_Expecter struct {
	mock *mock.Mock
}

func (_m *Registrar) EXPECT() *Registrar_Expecter {
	return &Registrar_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: _a0
func (_m *Registrar) Register(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Registrar_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Registrar_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *Registrar_Expecter) Register(_a0 interface{}) *Registrar_Register_Call {
	return &Registrar_Register_Call{Call: _e.mock.On("Register", _a0)}
}

func (_c *Registrar_Register_Call) Run(run func(_a0 context.Context)) *Registrar_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Registrar_Register_Call) Return(_a0 error) *Registrar_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Registrar_Register_Call) RunAndReturn(run func(context.Context) error) *Registrar_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistrar creates a new instance of Registrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registrar {
	mock := &Registrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
