// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	mock "github.com/stretchr/testify/mock"
)

// ISSMClient is an autogenerated mock type for the ISSMClient type
type ISSMClient struct {
	mock.Mock
}

type ISSMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ISSMClient) EXPECT() *ISSMClient_Expecter {
	return &ISSMClient_Expecter{mock: &_m.Mock}
}

// UpdateInstanceInformation provides a mock function with given fields: ctx, input, opts
func (_m *ISSMClient) UpdateInstanceInformation(ctx context.Context, input *ssm.UpdateInstanceInformationInput, opts ...func(*ssm.Options)) (*ssm.UpdateInstanceInformationOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInstanceInformation")
	}

	var r0 *ssm.UpdateInstanceInformationOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.UpdateInstanceInformationInput, ...func(*ssm.Options)) (*ssm.UpdateInstanceInformationOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ssm.UpdateInstanceInformationInput, ...func(*ssm.Options)) *ssm.UpdateInstanceInformationOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.UpdateInstanceInformationOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ssm.UpdateInstanceInformationInput, ...func(*ssm.Options)) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISSMClient_UpdateInstanceInformation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInstanceInformation'
type ISSMClient_UpdateInstanceInformation_Call struct {
	*mock.Call
}

// UpdateInstanceInformation is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.UpdateInstanceInformationInput
//   - opts ...func(*ssm.Options)
func (_e *ISSMClient_Expecter) UpdateInstanceInformation(ctx interface{}, input interface{}, opts ...interface{}) *ISSMClient_UpdateInstanceInformation_Call {
	return &ISSMClient_UpdateInstanceInformation_Call{Call: _e.mock.On("UpdateInstanceInformation",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *ISSMClient_UpdateInstanceInformation_Call) Run(run func(ctx context.Context, input *ssm.UpdateInstanceInformationInput, opts ...func(*ssm.Options))) *ISSMClient_UpdateInstanceInformation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*ssm.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*ssm.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*ssm.UpdateInstanceInformationInput), variadicArgs...)
	})
	return _c
}

func (_c *ISSMClient_UpdateInstanceInformation_Call) Return(_a0 *ssm.UpdateInstanceInformationOutput, _a1 error) *ISSMClient_UpdateInstanceInformation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISSMClient_UpdateInstanceInformation_Call) RunAndReturn(run func(context.Context, *ssm.UpdateInstanceInformationInput, ...func(*ssm.Options)) (*ssm.UpdateInstanceInformationOutput, error)) *ISSMClient_UpdateInstanceInformation_Call {
	_c.Call.Return(run)
	return _c
}

// NewISSMClient creates a new instance of ISSMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISSMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISSMClient {
	mock := &ISSMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
