// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/stretchr/testify/mock"
)

// ISharedCredentialsProvider is an autogenerated mock type for the ISharedCredentialsProvider type
type ISharedCredentialsProvider struct {
	mock.Mock
}

// ExpiresAt provides a mock function with given fields:
func (_m *ISharedCredentialsProvider) ExpiresAt() time.Time {
	ret := _m.Called()
	return ret.Get(0).(time.Time)
}

// IsExpired provides a mock function with given fields:
func (_m *ISharedCredentialsProvider) IsExpired() bool {
	ret := _m.Called()
	return ret.Get(0).(bool)
}

// NewSharedCredentials provides a mock function with given fields: sharedCredsFile, sharedProfile
func (_m *ISharedCredentialsProvider) NewSharedCredentials(sharedCredsFile string, sharedProfile string) (aws.Config, error) {
	ret := _m.Called(sharedCredsFile, sharedProfile)
	return ret.Get(0).(aws.Config), ret.Error(1)
}

// Retrieve provides a mock function with given fields: ctx
func (_m *ISharedCredentialsProvider) Retrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveWithContext provides a mock function with given fields: ctx
func (_m *ISharedCredentialsProvider) RetrieveWithContext(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
