// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/ssmmds"
	mock "github.com/stretchr/testify/mock"
)

// NewSsmmdsAPI creates a new instance of SsmmdsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSsmmdsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SsmmdsAPI {
	mock := &SsmmdsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SsmmdsAPI is an autogenerated mock type for the SsmmdsAPI type
type SsmmdsAPI struct {
	mock.Mock
}

type SsmmdsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SsmmdsAPI) EXPECT() *SsmmdsAPI_Expecter {
	return &SsmmdsAPI_Expecter{mock: &_m.Mock}
}

// AcknowledgeMessage provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) AcknowledgeMessage(acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput) (*ssmmds.AcknowledgeMessageOutput, error) {
	ret := _mock.Called(acknowledgeMessageInput)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeMessage")
	}

	var r0 *ssmmds.AcknowledgeMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.AcknowledgeMessageInput) (*ssmmds.AcknowledgeMessageOutput, error)); ok {
		return returnFunc(acknowledgeMessageInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.AcknowledgeMessageInput) *ssmmds.AcknowledgeMessageOutput); ok {
		r0 = returnFunc(acknowledgeMessageInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.AcknowledgeMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.AcknowledgeMessageInput) error); ok {
		r1 = returnFunc(acknowledgeMessageInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_AcknowledgeMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeMessage'
type SsmmdsAPI_AcknowledgeMessage_Call struct {
	*mock.Call
}

// AcknowledgeMessage is a helper method to define mock.On call
//   - acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput
func (_e *SsmmdsAPI_Expecter) AcknowledgeMessage(acknowledgeMessageInput interface{}) *SsmmdsAPI_AcknowledgeMessage_Call {
	return &SsmmdsAPI_AcknowledgeMessage_Call{Call: _e.mock.On("AcknowledgeMessage", acknowledgeMessageInput)}
}

func (_c *SsmmdsAPI_AcknowledgeMessage_Call) Run(run func(acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput)) *SsmmdsAPI_AcknowledgeMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.AcknowledgeMessageInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.AcknowledgeMessageInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_AcknowledgeMessage_Call) Return(acknowledgeMessageOutput *ssmmds.AcknowledgeMessageOutput, err error) *SsmmdsAPI_AcknowledgeMessage_Call {
	_c.Call.Return(acknowledgeMessageOutput, err)
	return _c
}

func (_c *SsmmdsAPI_AcknowledgeMessage_Call) RunAndReturn(run func(acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput) (*ssmmds.AcknowledgeMessageOutput, error)) *SsmmdsAPI_AcknowledgeMessage_Call {
	_c.Call.Return(run)
	return _c
}

// AcknowledgeMessageRequest provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) AcknowledgeMessageRequest(acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput) (*request.Request, *ssmmds.AcknowledgeMessageOutput) {
	ret := _mock.Called(acknowledgeMessageInput)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeMessageRequest")
	}

	var r0 *request.Request
	var r1 *ssmmds.AcknowledgeMessageOutput
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.AcknowledgeMessageInput) (*request.Request, *ssmmds.AcknowledgeMessageOutput)); ok {
		return returnFunc(acknowledgeMessageInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.AcknowledgeMessageInput) *request.Request); ok {
		r0 = returnFunc(acknowledgeMessageInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.AcknowledgeMessageInput) *ssmmds.AcknowledgeMessageOutput); ok {
		r1 = returnFunc(acknowledgeMessageInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ssmmds.AcknowledgeMessageOutput)
		}
	}
	return r0, r1
}

// SsmmdsAPI_AcknowledgeMessageRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeMessageRequest'
type SsmmdsAPI_AcknowledgeMessageRequest_Call struct {
	*mock.Call
}

// AcknowledgeMessageRequest is a helper method to define mock.On call
//   - acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput
func (_e *SsmmdsAPI_Expecter) AcknowledgeMessageRequest(acknowledgeMessageInput interface{}) *SsmmdsAPI_AcknowledgeMessageRequest_Call {
	return &SsmmdsAPI_AcknowledgeMessageRequest_Call{Call: _e.mock.On("AcknowledgeMessageRequest", acknowledgeMessageInput)}
}

func (_c *SsmmdsAPI_AcknowledgeMessageRequest_Call) Run(run func(acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput)) *SsmmdsAPI_AcknowledgeMessageRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.AcknowledgeMessageInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.AcknowledgeMessageInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_AcknowledgeMessageRequest_Call) Return(request1 *request.Request, acknowledgeMessageOutput *ssmmds.AcknowledgeMessageOutput) *SsmmdsAPI_AcknowledgeMessageRequest_Call {
	_c.Call.Return(request1, acknowledgeMessageOutput)
	return _c
}

func (_c *SsmmdsAPI_AcknowledgeMessageRequest_Call) RunAndReturn(run func(acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput) (*request.Request, *ssmmds.AcknowledgeMessageOutput)) *SsmmdsAPI_AcknowledgeMessageRequest_Call {
	_c.Call.Return(run)
	return _c
}

// AcknowledgeMessageWithContext provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) AcknowledgeMessageWithContext(v aws.Context, acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput, options ...request.Option) (*ssmmds.AcknowledgeMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, acknowledgeMessageInput, options)
	} else {
		tmpRet = _mock.Called(v, acknowledgeMessageInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeMessageWithContext")
	}

	var r0 *ssmmds.AcknowledgeMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.AcknowledgeMessageInput, ...request.Option) (*ssmmds.AcknowledgeMessageOutput, error)); ok {
		return returnFunc(v, acknowledgeMessageInput, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.AcknowledgeMessageInput, ...request.Option) *ssmmds.AcknowledgeMessageOutput); ok {
		r0 = returnFunc(v, acknowledgeMessageInput, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.AcknowledgeMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aws.Context, *ssmmds.AcknowledgeMessageInput, ...request.Option) error); ok {
		r1 = returnFunc(v, acknowledgeMessageInput, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_AcknowledgeMessageWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcknowledgeMessageWithContext'
type SsmmdsAPI_AcknowledgeMessageWithContext_Call struct {
	*mock.Call
}

// AcknowledgeMessageWithContext is a helper method to define mock.On call
//   - v aws.Context
//   - acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput
//   - options ...request.Option
func (_e *SsmmdsAPI_Expecter) AcknowledgeMessageWithContext(v interface{}, acknowledgeMessageInput interface{}, options ...interface{}) *SsmmdsAPI_AcknowledgeMessageWithContext_Call {
	return &SsmmdsAPI_AcknowledgeMessageWithContext_Call{Call: _e.mock.On("AcknowledgeMessageWithContext",
		append([]interface{}{v, acknowledgeMessageInput}, options...)...)}
}

func (_c *SsmmdsAPI_AcknowledgeMessageWithContext_Call) Run(run func(v aws.Context, acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput, options ...request.Option)) *SsmmdsAPI_AcknowledgeMessageWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aws.Context
		if args[0] != nil {
			arg0 = args[0].(aws.Context)
		}
		var arg1 *ssmmds.AcknowledgeMessageInput
		if args[1] != nil {
			arg1 = args[1].(*ssmmds.AcknowledgeMessageInput)
		}
		var arg2 []request.Option
		var variadicArgs []request.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]request.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_AcknowledgeMessageWithContext_Call) Return(acknowledgeMessageOutput *ssmmds.AcknowledgeMessageOutput, err error) *SsmmdsAPI_AcknowledgeMessageWithContext_Call {
	_c.Call.Return(acknowledgeMessageOutput, err)
	return _c
}

func (_c *SsmmdsAPI_AcknowledgeMessageWithContext_Call) RunAndReturn(run func(v aws.Context, acknowledgeMessageInput *ssmmds.AcknowledgeMessageInput, options ...request.Option) (*ssmmds.AcknowledgeMessageOutput, error)) *SsmmdsAPI_AcknowledgeMessageWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) DeleteMessage(deleteMessageInput *ssmmds.DeleteMessageInput) (*ssmmds.DeleteMessageOutput, error) {
	ret := _mock.Called(deleteMessageInput)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 *ssmmds.DeleteMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.DeleteMessageInput) (*ssmmds.DeleteMessageOutput, error)); ok {
		return returnFunc(deleteMessageInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.DeleteMessageInput) *ssmmds.DeleteMessageOutput); ok {
		r0 = returnFunc(deleteMessageInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.DeleteMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.DeleteMessageInput) error); ok {
		r1 = returnFunc(deleteMessageInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type SsmmdsAPI_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - deleteMessageInput *ssmmds.DeleteMessageInput
func (_e *SsmmdsAPI_Expecter) DeleteMessage(deleteMessageInput interface{}) *SsmmdsAPI_DeleteMessage_Call {
	return &SsmmdsAPI_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", deleteMessageInput)}
}

func (_c *SsmmdsAPI_DeleteMessage_Call) Run(run func(deleteMessageInput *ssmmds.DeleteMessageInput)) *SsmmdsAPI_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.DeleteMessageInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.DeleteMessageInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_DeleteMessage_Call) Return(deleteMessageOutput *ssmmds.DeleteMessageOutput, err error) *SsmmdsAPI_DeleteMessage_Call {
	_c.Call.Return(deleteMessageOutput, err)
	return _c
}

func (_c *SsmmdsAPI_DeleteMessage_Call) RunAndReturn(run func(deleteMessageInput *ssmmds.DeleteMessageInput) (*ssmmds.DeleteMessageOutput, error)) *SsmmdsAPI_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessageRequest provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) DeleteMessageRequest(deleteMessageInput *ssmmds.DeleteMessageInput) (*request.Request, *ssmmds.DeleteMessageOutput) {
	ret := _mock.Called(deleteMessageInput)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessageRequest")
	}

	var r0 *request.Request
	var r1 *ssmmds.DeleteMessageOutput
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.DeleteMessageInput) (*request.Request, *ssmmds.DeleteMessageOutput)); ok {
		return returnFunc(deleteMessageInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.DeleteMessageInput) *request.Request); ok {
		r0 = returnFunc(deleteMessageInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.DeleteMessageInput) *ssmmds.DeleteMessageOutput); ok {
		r1 = returnFunc(deleteMessageInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ssmmds.DeleteMessageOutput)
		}
	}
	return r0, r1
}

// SsmmdsAPI_DeleteMessageRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessageRequest'
type SsmmdsAPI_DeleteMessageRequest_Call struct {
	*mock.Call
}

// DeleteMessageRequest is a helper method to define mock.On call
//   - deleteMessageInput *ssmmds.DeleteMessageInput
func (_e *SsmmdsAPI_Expecter) DeleteMessageRequest(deleteMessageInput interface{}) *SsmmdsAPI_DeleteMessageRequest_Call {
	return &SsmmdsAPI_DeleteMessageRequest_Call{Call: _e.mock.On("DeleteMessageRequest", deleteMessageInput)}
}

func (_c *SsmmdsAPI_DeleteMessageRequest_Call) Run(run func(deleteMessageInput *ssmmds.DeleteMessageInput)) *SsmmdsAPI_DeleteMessageRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.DeleteMessageInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.DeleteMessageInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_DeleteMessageRequest_Call) Return(request1 *request.Request, deleteMessageOutput *ssmmds.DeleteMessageOutput) *SsmmdsAPI_DeleteMessageRequest_Call {
	_c.Call.Return(request1, deleteMessageOutput)
	return _c
}

func (_c *SsmmdsAPI_DeleteMessageRequest_Call) RunAndReturn(run func(deleteMessageInput *ssmmds.DeleteMessageInput) (*request.Request, *ssmmds.DeleteMessageOutput)) *SsmmdsAPI_DeleteMessageRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessageWithContext provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) DeleteMessageWithContext(v aws.Context, deleteMessageInput *ssmmds.DeleteMessageInput, options ...request.Option) (*ssmmds.DeleteMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, deleteMessageInput, options)
	} else {
		tmpRet = _mock.Called(v, deleteMessageInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessageWithContext")
	}

	var r0 *ssmmds.DeleteMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.DeleteMessageInput, ...request.Option) (*ssmmds.DeleteMessageOutput, error)); ok {
		return returnFunc(v, deleteMessageInput, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.DeleteMessageInput, ...request.Option) *ssmmds.DeleteMessageOutput); ok {
		r0 = returnFunc(v, deleteMessageInput, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.DeleteMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aws.Context, *ssmmds.DeleteMessageInput, ...request.Option) error); ok {
		r1 = returnFunc(v, deleteMessageInput, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_DeleteMessageWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessageWithContext'
type SsmmdsAPI_DeleteMessageWithContext_Call struct {
	*mock.Call
}

// DeleteMessageWithContext is a helper method to define mock.On call
//   - v aws.Context
//   - deleteMessageInput *ssmmds.DeleteMessageInput
//   - options ...request.Option
func (_e *SsmmdsAPI_Expecter) DeleteMessageWithContext(v interface{}, deleteMessageInput interface{}, options ...interface{}) *SsmmdsAPI_DeleteMessageWithContext_Call {
	return &SsmmdsAPI_DeleteMessageWithContext_Call{Call: _e.mock.On("DeleteMessageWithContext",
		append([]interface{}{v, deleteMessageInput}, options...)...)}
}

func (_c *SsmmdsAPI_DeleteMessageWithContext_Call) Run(run func(v aws.Context, deleteMessageInput *ssmmds.DeleteMessageInput, options ...request.Option)) *SsmmdsAPI_DeleteMessageWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aws.Context
		if args[0] != nil {
			arg0 = args[0].(aws.Context)
		}
		var arg1 *ssmmds.DeleteMessageInput
		if args[1] != nil {
			arg1 = args[1].(*ssmmds.DeleteMessageInput)
		}
		var arg2 []request.Option
		var variadicArgs []request.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]request.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_DeleteMessageWithContext_Call) Return(deleteMessageOutput *ssmmds.DeleteMessageOutput, err error) *SsmmdsAPI_DeleteMessageWithContext_Call {
	_c.Call.Return(deleteMessageOutput, err)
	return _c
}

func (_c *SsmmdsAPI_DeleteMessageWithContext_Call) RunAndReturn(run func(v aws.Context, deleteMessageInput *ssmmds.DeleteMessageInput, options ...request.Option) (*ssmmds.DeleteMessageOutput, error)) *SsmmdsAPI_DeleteMessageWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// FailMessage provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) FailMessage(failMessageInput *ssmmds.FailMessageInput) (*ssmmds.FailMessageOutput, error) {
	ret := _mock.Called(failMessageInput)

	if len(ret) == 0 {
		panic("no return value specified for FailMessage")
	}

	var r0 *ssmmds.FailMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.FailMessageInput) (*ssmmds.FailMessageOutput, error)); ok {
		return returnFunc(failMessageInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.FailMessageInput) *ssmmds.FailMessageOutput); ok {
		r0 = returnFunc(failMessageInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.FailMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.FailMessageInput) error); ok {
		r1 = returnFunc(failMessageInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_FailMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailMessage'
type SsmmdsAPI_FailMessage_Call struct {
	*mock.Call
}

// FailMessage is a helper method to define mock.On call
//   - failMessageInput *ssmmds.FailMessageInput
func (_e *SsmmdsAPI_Expecter) FailMessage(failMessageInput interface{}) *SsmmdsAPI_FailMessage_Call {
	return &SsmmdsAPI_FailMessage_Call{Call: _e.mock.On("FailMessage", failMessageInput)}
}

func (_c *SsmmdsAPI_FailMessage_Call) Run(run func(failMessageInput *ssmmds.FailMessageInput)) *SsmmdsAPI_FailMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.FailMessageInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.FailMessageInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_FailMessage_Call) Return(failMessageOutput *ssmmds.FailMessageOutput, err error) *SsmmdsAPI_FailMessage_Call {
	_c.Call.Return(failMessageOutput, err)
	return _c
}

func (_c *SsmmdsAPI_FailMessage_Call) RunAndReturn(run func(failMessageInput *ssmmds.FailMessageInput) (*ssmmds.FailMessageOutput, error)) *SsmmdsAPI_FailMessage_Call {
	_c.Call.Return(run)
	return _c
}

// FailMessageRequest provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) FailMessageRequest(failMessageInput *ssmmds.FailMessageInput) (*request.Request, *ssmmds.FailMessageOutput) {
	ret := _mock.Called(failMessageInput)

	if len(ret) == 0 {
		panic("no return value specified for FailMessageRequest")
	}

	var r0 *request.Request
	var r1 *ssmmds.FailMessageOutput
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.FailMessageInput) (*request.Request, *ssmmds.FailMessageOutput)); ok {
		return returnFunc(failMessageInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.FailMessageInput) *request.Request); ok {
		r0 = returnFunc(failMessageInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.FailMessageInput) *ssmmds.FailMessageOutput); ok {
		r1 = returnFunc(failMessageInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ssmmds.FailMessageOutput)
		}
	}
	return r0, r1
}

// SsmmdsAPI_FailMessageRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailMessageRequest'
type SsmmdsAPI_FailMessageRequest_Call struct {
	*mock.Call
}

// FailMessageRequest is a helper method to define mock.On call
//   - failMessageInput *ssmmds.FailMessageInput
func (_e *SsmmdsAPI_Expecter) FailMessageRequest(failMessageInput interface{}) *SsmmdsAPI_FailMessageRequest_Call {
	return &SsmmdsAPI_FailMessageRequest_Call{Call: _e.mock.On("FailMessageRequest", failMessageInput)}
}

func (_c *SsmmdsAPI_FailMessageRequest_Call) Run(run func(failMessageInput *ssmmds.FailMessageInput)) *SsmmdsAPI_FailMessageRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.FailMessageInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.FailMessageInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_FailMessageRequest_Call) Return(request1 *request.Request, failMessageOutput *ssmmds.FailMessageOutput) *SsmmdsAPI_FailMessageRequest_Call {
	_c.Call.Return(request1, failMessageOutput)
	return _c
}

func (_c *SsmmdsAPI_FailMessageRequest_Call) RunAndReturn(run func(failMessageInput *ssmmds.FailMessageInput) (*request.Request, *ssmmds.FailMessageOutput)) *SsmmdsAPI_FailMessageRequest_Call {
	_c.Call.Return(run)
	return _c
}

// FailMessageWithContext provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) FailMessageWithContext(v aws.Context, failMessageInput *ssmmds.FailMessageInput, options ...request.Option) (*ssmmds.FailMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, failMessageInput, options)
	} else {
		tmpRet = _mock.Called(v, failMessageInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FailMessageWithContext")
	}

	var r0 *ssmmds.FailMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.FailMessageInput, ...request.Option) (*ssmmds.FailMessageOutput, error)); ok {
		return returnFunc(v, failMessageInput, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.FailMessageInput, ...request.Option) *ssmmds.FailMessageOutput); ok {
		r0 = returnFunc(v, failMessageInput, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.FailMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aws.Context, *ssmmds.FailMessageInput, ...request.Option) error); ok {
		r1 = returnFunc(v, failMessageInput, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_FailMessageWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailMessageWithContext'
type SsmmdsAPI_FailMessageWithContext_Call struct {
	*mock.Call
}

// FailMessageWithContext is a helper method to define mock.On call
//   - v aws.Context
//   - failMessageInput *ssmmds.FailMessageInput
//   - options ...request.Option
func (_e *SsmmdsAPI_Expecter) FailMessageWithContext(v interface{}, failMessageInput interface{}, options ...interface{}) *SsmmdsAPI_FailMessageWithContext_Call {
	return &SsmmdsAPI_FailMessageWithContext_Call{Call: _e.mock.On("FailMessageWithContext",
		append([]interface{}{v, failMessageInput}, options...)...)}
}

func (_c *SsmmdsAPI_FailMessageWithContext_Call) Run(run func(v aws.Context, failMessageInput *ssmmds.FailMessageInput, options ...request.Option)) *SsmmdsAPI_FailMessageWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aws.Context
		if args[0] != nil {
			arg0 = args[0].(aws.Context)
		}
		var arg1 *ssmmds.FailMessageInput
		if args[1] != nil {
			arg1 = args[1].(*ssmmds.FailMessageInput)
		}
		var arg2 []request.Option
		var variadicArgs []request.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]request.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_FailMessageWithContext_Call) Return(failMessageOutput *ssmmds.FailMessageOutput, err error) *SsmmdsAPI_FailMessageWithContext_Call {
	_c.Call.Return(failMessageOutput, err)
	return _c
}

func (_c *SsmmdsAPI_FailMessageWithContext_Call) RunAndReturn(run func(v aws.Context, failMessageInput *ssmmds.FailMessageInput, options ...request.Option) (*ssmmds.FailMessageOutput, error)) *SsmmdsAPI_FailMessageWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpoint provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) GetEndpoint(getEndpointInput *ssmmds.GetEndpointInput) (*ssmmds.GetEndpointOutput, error) {
	ret := _mock.Called(getEndpointInput)

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 *ssmmds.GetEndpointOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetEndpointInput) (*ssmmds.GetEndpointOutput, error)); ok {
		return returnFunc(getEndpointInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetEndpointInput) *ssmmds.GetEndpointOutput); ok {
		r0 = returnFunc(getEndpointInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.GetEndpointOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.GetEndpointInput) error); ok {
		r1 = returnFunc(getEndpointInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type SsmmdsAPI_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
//   - getEndpointInput *ssmmds.GetEndpointInput
func (_e *SsmmdsAPI_Expecter) GetEndpoint(getEndpointInput interface{}) *SsmmdsAPI_GetEndpoint_Call {
	return &SsmmdsAPI_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint", getEndpointInput)}
}

func (_c *SsmmdsAPI_GetEndpoint_Call) Run(run func(getEndpointInput *ssmmds.GetEndpointInput)) *SsmmdsAPI_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.GetEndpointInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.GetEndpointInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_GetEndpoint_Call) Return(getEndpointOutput *ssmmds.GetEndpointOutput, err error) *SsmmdsAPI_GetEndpoint_Call {
	_c.Call.Return(getEndpointOutput, err)
	return _c
}

func (_c *SsmmdsAPI_GetEndpoint_Call) RunAndReturn(run func(getEndpointInput *ssmmds.GetEndpointInput) (*ssmmds.GetEndpointOutput, error)) *SsmmdsAPI_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpointRequest provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) GetEndpointRequest(getEndpointInput *ssmmds.GetEndpointInput) (*request.Request, *ssmmds.GetEndpointOutput) {
	ret := _mock.Called(getEndpointInput)

	if len(ret) == 0 {
		panic("no return value specified for GetEndpointRequest")
	}

	var r0 *request.Request
	var r1 *ssmmds.GetEndpointOutput
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetEndpointInput) (*request.Request, *ssmmds.GetEndpointOutput)); ok {
		return returnFunc(getEndpointInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetEndpointInput) *request.Request); ok {
		r0 = returnFunc(getEndpointInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.GetEndpointInput) *ssmmds.GetEndpointOutput); ok {
		r1 = returnFunc(getEndpointInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ssmmds.GetEndpointOutput)
		}
	}
	return r0, r1
}

// SsmmdsAPI_GetEndpointRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpointRequest'
type SsmmdsAPI_GetEndpointRequest_Call struct {
	*mock.Call
}

// GetEndpointRequest is a helper method to define mock.On call
//   - getEndpointInput *ssmmds.GetEndpointInput
func (_e *SsmmdsAPI_Expecter) GetEndpointRequest(getEndpointInput interface{}) *SsmmdsAPI_GetEndpointRequest_Call {
	return &SsmmdsAPI_GetEndpointRequest_Call{Call: _e.mock.On("GetEndpointRequest", getEndpointInput)}
}

func (_c *SsmmdsAPI_GetEndpointRequest_Call) Run(run func(getEndpointInput *ssmmds.GetEndpointInput)) *SsmmdsAPI_GetEndpointRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.GetEndpointInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.GetEndpointInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_GetEndpointRequest_Call) Return(request1 *request.Request, getEndpointOutput *ssmmds.GetEndpointOutput) *SsmmdsAPI_GetEndpointRequest_Call {
	_c.Call.Return(request1, getEndpointOutput)
	return _c
}

func (_c *SsmmdsAPI_GetEndpointRequest_Call) RunAndReturn(run func(getEndpointInput *ssmmds.GetEndpointInput) (*request.Request, *ssmmds.GetEndpointOutput)) *SsmmdsAPI_GetEndpointRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpointWithContext provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) GetEndpointWithContext(v aws.Context, getEndpointInput *ssmmds.GetEndpointInput, options ...request.Option) (*ssmmds.GetEndpointOutput, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, getEndpointInput, options)
	} else {
		tmpRet = _mock.Called(v, getEndpointInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetEndpointWithContext")
	}

	var r0 *ssmmds.GetEndpointOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.GetEndpointInput, ...request.Option) (*ssmmds.GetEndpointOutput, error)); ok {
		return returnFunc(v, getEndpointInput, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.GetEndpointInput, ...request.Option) *ssmmds.GetEndpointOutput); ok {
		r0 = returnFunc(v, getEndpointInput, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.GetEndpointOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aws.Context, *ssmmds.GetEndpointInput, ...request.Option) error); ok {
		r1 = returnFunc(v, getEndpointInput, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_GetEndpointWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpointWithContext'
type SsmmdsAPI_GetEndpointWithContext_Call struct {
	*mock.Call
}

// GetEndpointWithContext is a helper method to define mock.On call
//   - v aws.Context
//   - getEndpointInput *ssmmds.GetEndpointInput
//   - options ...request.Option
func (_e *SsmmdsAPI_Expecter) GetEndpointWithContext(v interface{}, getEndpointInput interface{}, options ...interface{}) *SsmmdsAPI_GetEndpointWithContext_Call {
	return &SsmmdsAPI_GetEndpointWithContext_Call{Call: _e.mock.On("GetEndpointWithContext",
		append([]interface{}{v, getEndpointInput}, options...)...)}
}

func (_c *SsmmdsAPI_GetEndpointWithContext_Call) Run(run func(v aws.Context, getEndpointInput *ssmmds.GetEndpointInput, options ...request.Option)) *SsmmdsAPI_GetEndpointWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aws.Context
		if args[0] != nil {
			arg0 = args[0].(aws.Context)
		}
		var arg1 *ssmmds.GetEndpointInput
		if args[1] != nil {
			arg1 = args[1].(*ssmmds.GetEndpointInput)
		}
		var arg2 []request.Option
		var variadicArgs []request.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]request.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_GetEndpointWithContext_Call) Return(getEndpointOutput *ssmmds.GetEndpointOutput, err error) *SsmmdsAPI_GetEndpointWithContext_Call {
	_c.Call.Return(getEndpointOutput, err)
	return _c
}

func (_c *SsmmdsAPI_GetEndpointWithContext_Call) RunAndReturn(run func(v aws.Context, getEndpointInput *ssmmds.GetEndpointInput, options ...request.Option) (*ssmmds.GetEndpointOutput, error)) *SsmmdsAPI_GetEndpointWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) GetMessages(getMessagesInput *ssmmds.GetMessagesInput) (*ssmmds.GetMessagesOutput, error) {
	ret := _mock.Called(getMessagesInput)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 *ssmmds.GetMessagesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetMessagesInput) (*ssmmds.GetMessagesOutput, error)); ok {
		return returnFunc(getMessagesInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetMessagesInput) *ssmmds.GetMessagesOutput); ok {
		r0 = returnFunc(getMessagesInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.GetMessagesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.GetMessagesInput) error); ok {
		r1 = returnFunc(getMessagesInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type SsmmdsAPI_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - getMessagesInput *ssmmds.GetMessagesInput
func (_e *SsmmdsAPI_Expecter) GetMessages(getMessagesInput interface{}) *SsmmdsAPI_GetMessages_Call {
	return &SsmmdsAPI_GetMessages_Call{Call: _e.mock.On("GetMessages", getMessagesInput)}
}

func (_c *SsmmdsAPI_GetMessages_Call) Run(run func(getMessagesInput *ssmmds.GetMessagesInput)) *SsmmdsAPI_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.GetMessagesInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.GetMessagesInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_GetMessages_Call) Return(getMessagesOutput *ssmmds.GetMessagesOutput, err error) *SsmmdsAPI_GetMessages_Call {
	_c.Call.Return(getMessagesOutput, err)
	return _c
}

func (_c *SsmmdsAPI_GetMessages_Call) RunAndReturn(run func(getMessagesInput *ssmmds.GetMessagesInput) (*ssmmds.GetMessagesOutput, error)) *SsmmdsAPI_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesRequest provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) GetMessagesRequest(getMessagesInput *ssmmds.GetMessagesInput) (*request.Request, *ssmmds.GetMessagesOutput) {
	ret := _mock.Called(getMessagesInput)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesRequest")
	}

	var r0 *request.Request
	var r1 *ssmmds.GetMessagesOutput
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetMessagesInput) (*request.Request, *ssmmds.GetMessagesOutput)); ok {
		return returnFunc(getMessagesInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.GetMessagesInput) *request.Request); ok {
		r0 = returnFunc(getMessagesInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.GetMessagesInput) *ssmmds.GetMessagesOutput); ok {
		r1 = returnFunc(getMessagesInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ssmmds.GetMessagesOutput)
		}
	}
	return r0, r1
}

// SsmmdsAPI_GetMessagesRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesRequest'
type SsmmdsAPI_GetMessagesRequest_Call struct {
	*mock.Call
}

// GetMessagesRequest is a helper method to define mock.On call
//   - getMessagesInput *ssmmds.GetMessagesInput
func (_e *SsmmdsAPI_Expecter) GetMessagesRequest(getMessagesInput interface{}) *SsmmdsAPI_GetMessagesRequest_Call {
	return &SsmmdsAPI_GetMessagesRequest_Call{Call: _e.mock.On("GetMessagesRequest", getMessagesInput)}
}

func (_c *SsmmdsAPI_GetMessagesRequest_Call) Run(run func(getMessagesInput *ssmmds.GetMessagesInput)) *SsmmdsAPI_GetMessagesRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.GetMessagesInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.GetMessagesInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_GetMessagesRequest_Call) Return(request1 *request.Request, getMessagesOutput *ssmmds.GetMessagesOutput) *SsmmdsAPI_GetMessagesRequest_Call {
	_c.Call.Return(request1, getMessagesOutput)
	return _c
}

func (_c *SsmmdsAPI_GetMessagesRequest_Call) RunAndReturn(run func(getMessagesInput *ssmmds.GetMessagesInput) (*request.Request, *ssmmds.GetMessagesOutput)) *SsmmdsAPI_GetMessagesRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesWithContext provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) GetMessagesWithContext(v aws.Context, getMessagesInput *ssmmds.GetMessagesInput, options ...request.Option) (*ssmmds.GetMessagesOutput, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, getMessagesInput, options)
	} else {
		tmpRet = _mock.Called(v, getMessagesInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesWithContext")
	}

	var r0 *ssmmds.GetMessagesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.GetMessagesInput, ...request.Option) (*ssmmds.GetMessagesOutput, error)); ok {
		return returnFunc(v, getMessagesInput, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.GetMessagesInput, ...request.Option) *ssmmds.GetMessagesOutput); ok {
		r0 = returnFunc(v, getMessagesInput, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.GetMessagesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aws.Context, *ssmmds.GetMessagesInput, ...request.Option) error); ok {
		r1 = returnFunc(v, getMessagesInput, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_GetMessagesWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesWithContext'
type SsmmdsAPI_GetMessagesWithContext_Call struct {
	*mock.Call
}

// GetMessagesWithContext is a helper method to define mock.On call
//   - v aws.Context
//   - getMessagesInput *ssmmds.GetMessagesInput
//   - options ...request.Option
func (_e *SsmmdsAPI_Expecter) GetMessagesWithContext(v interface{}, getMessagesInput interface{}, options ...interface{}) *SsmmdsAPI_GetMessagesWithContext_Call {
	return &SsmmdsAPI_GetMessagesWithContext_Call{Call: _e.mock.On("GetMessagesWithContext",
		append([]interface{}{v, getMessagesInput}, options...)...)}
}

func (_c *SsmmdsAPI_GetMessagesWithContext_Call) Run(run func(v aws.Context, getMessagesInput *ssmmds.GetMessagesInput, options ...request.Option)) *SsmmdsAPI_GetMessagesWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aws.Context
		if args[0] != nil {
			arg0 = args[0].(aws.Context)
		}
		var arg1 *ssmmds.GetMessagesInput
		if args[1] != nil {
			arg1 = args[1].(*ssmmds.GetMessagesInput)
		}
		var arg2 []request.Option
		var variadicArgs []request.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]request.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_GetMessagesWithContext_Call) Return(getMessagesOutput *ssmmds.GetMessagesOutput, err error) *SsmmdsAPI_GetMessagesWithContext_Call {
	_c.Call.Return(getMessagesOutput, err)
	return _c
}

func (_c *SsmmdsAPI_GetMessagesWithContext_Call) RunAndReturn(run func(v aws.Context, getMessagesInput *ssmmds.GetMessagesInput, options ...request.Option) (*ssmmds.GetMessagesOutput, error)) *SsmmdsAPI_GetMessagesWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// SendReply provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) SendReply(sendReplyInput *ssmmds.SendReplyInput) (*ssmmds.SendReplyOutput, error) {
	ret := _mock.Called(sendReplyInput)

	if len(ret) == 0 {
		panic("no return value specified for SendReply")
	}

	var r0 *ssmmds.SendReplyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.SendReplyInput) (*ssmmds.SendReplyOutput, error)); ok {
		return returnFunc(sendReplyInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.SendReplyInput) *ssmmds.SendReplyOutput); ok {
		r0 = returnFunc(sendReplyInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.SendReplyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.SendReplyInput) error); ok {
		r1 = returnFunc(sendReplyInput)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_SendReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReply'
type SsmmdsAPI_SendReply_Call struct {
	*mock.Call
}

// SendReply is a helper method to define mock.On call
//   - sendReplyInput *ssmmds.SendReplyInput
func (_e *SsmmdsAPI_Expecter) SendReply(sendReplyInput interface{}) *SsmmdsAPI_SendReply_Call {
	return &SsmmdsAPI_SendReply_Call{Call: _e.mock.On("SendReply", sendReplyInput)}
}

func (_c *SsmmdsAPI_SendReply_Call) Run(run func(sendReplyInput *ssmmds.SendReplyInput)) *SsmmdsAPI_SendReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.SendReplyInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.SendReplyInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_SendReply_Call) Return(sendReplyOutput *ssmmds.SendReplyOutput, err error) *SsmmdsAPI_SendReply_Call {
	_c.Call.Return(sendReplyOutput, err)
	return _c
}

func (_c *SsmmdsAPI_SendReply_Call) RunAndReturn(run func(sendReplyInput *ssmmds.SendReplyInput) (*ssmmds.SendReplyOutput, error)) *SsmmdsAPI_SendReply_Call {
	_c.Call.Return(run)
	return _c
}

// SendReplyRequest provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) SendReplyRequest(sendReplyInput *ssmmds.SendReplyInput) (*request.Request, *ssmmds.SendReplyOutput) {
	ret := _mock.Called(sendReplyInput)

	if len(ret) == 0 {
		panic("no return value specified for SendReplyRequest")
	}

	var r0 *request.Request
	var r1 *ssmmds.SendReplyOutput
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.SendReplyInput) (*request.Request, *ssmmds.SendReplyOutput)); ok {
		return returnFunc(sendReplyInput)
	}
	if returnFunc, ok := ret.Get(0).(func(*ssmmds.SendReplyInput) *request.Request); ok {
		r0 = returnFunc(sendReplyInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*request.Request)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*ssmmds.SendReplyInput) *ssmmds.SendReplyOutput); ok {
		r1 = returnFunc(sendReplyInput)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ssmmds.SendReplyOutput)
		}
	}
	return r0, r1
}

// SsmmdsAPI_SendReplyRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReplyRequest'
type SsmmdsAPI_SendReplyRequest_Call struct {
	*mock.Call
}

// SendReplyRequest is a helper method to define mock.On call
//   - sendReplyInput *ssmmds.SendReplyInput
func (_e *SsmmdsAPI_Expecter) SendReplyRequest(sendReplyInput interface{}) *SsmmdsAPI_SendReplyRequest_Call {
	return &SsmmdsAPI_SendReplyRequest_Call{Call: _e.mock.On("SendReplyRequest", sendReplyInput)}
}

func (_c *SsmmdsAPI_SendReplyRequest_Call) Run(run func(sendReplyInput *ssmmds.SendReplyInput)) *SsmmdsAPI_SendReplyRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssmmds.SendReplyInput
		if args[0] != nil {
			arg0 = args[0].(*ssmmds.SendReplyInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_SendReplyRequest_Call) Return(request1 *request.Request, sendReplyOutput *ssmmds.SendReplyOutput) *SsmmdsAPI_SendReplyRequest_Call {
	_c.Call.Return(request1, sendReplyOutput)
	return _c
}

func (_c *SsmmdsAPI_SendReplyRequest_Call) RunAndReturn(run func(sendReplyInput *ssmmds.SendReplyInput) (*request.Request, *ssmmds.SendReplyOutput)) *SsmmdsAPI_SendReplyRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SendReplyWithContext provides a mock function for the type SsmmdsAPI
func (_mock *SsmmdsAPI) SendReplyWithContext(v aws.Context, sendReplyInput *ssmmds.SendReplyInput, options ...request.Option) (*ssmmds.SendReplyOutput, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, sendReplyInput, options)
	} else {
		tmpRet = _mock.Called(v, sendReplyInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendReplyWithContext")
	}

	var r0 *ssmmds.SendReplyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.SendReplyInput, ...request.Option) (*ssmmds.SendReplyOutput, error)); ok {
		return returnFunc(v, sendReplyInput, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aws.Context, *ssmmds.SendReplyInput, ...request.Option) *ssmmds.SendReplyOutput); ok {
		r0 = returnFunc(v, sendReplyInput, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssmmds.SendReplyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aws.Context, *ssmmds.SendReplyInput, ...request.Option) error); ok {
		r1 = returnFunc(v, sendReplyInput, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SsmmdsAPI_SendReplyWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReplyWithContext'
type SsmmdsAPI_SendReplyWithContext_Call struct {
	*mock.Call
}

// SendReplyWithContext is a helper method to define mock.On call
//   - v aws.Context
//   - sendReplyInput *ssmmds.SendReplyInput
//   - options ...request.Option
func (_e *SsmmdsAPI_Expecter) SendReplyWithContext(v interface{}, sendReplyInput interface{}, options ...interface{}) *SsmmdsAPI_SendReplyWithContext_Call {
	return &SsmmdsAPI_SendReplyWithContext_Call{Call: _e.mock.On("SendReplyWithContext",
		append([]interface{}{v, sendReplyInput}, options...)...)}
}

func (_c *SsmmdsAPI_SendReplyWithContext_Call) Run(run func(v aws.Context, sendReplyInput *ssmmds.SendReplyInput, options ...request.Option)) *SsmmdsAPI_SendReplyWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aws.Context
		if args[0] != nil {
			arg0 = args[0].(aws.Context)
		}
		var arg1 *ssmmds.SendReplyInput
		if args[1] != nil {
			arg1 = args[1].(*ssmmds.SendReplyInput)
		}
		var arg2 []request.Option
		var variadicArgs []request.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]request.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SsmmdsAPI_SendReplyWithContext_Call) Return(sendReplyOutput *ssmmds.SendReplyOutput, err error) *SsmmdsAPI_SendReplyWithContext_Call {
	_c.Call.Return(sendReplyOutput, err)
	return _c
}

func (_c *SsmmdsAPI_SendReplyWithContext_Call) RunAndReturn(run func(v aws.Context, sendReplyInput *ssmmds.SendReplyInput, options ...request.Option) (*ssmmds.SendReplyOutput, error)) *SsmmdsAPI_SendReplyWithContext_Call {
	_c.Call.Return(run)
	return _c
}
