// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	aws "github.com/aws/aws-sdk-go-v2/aws"

	mock "github.com/stretchr/testify/mock"
)

// CredentialsProvider is an autogenerated mock type for the CredentialsProvider type
type CredentialsProvider struct {
	mock.Mock
}

type CredentialsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *CredentialsProvider) EXPECT() *CredentialsProvider_Expecter {
	return &CredentialsProvider_Expecter{mock: &_m.Mock}
}

// Retrieve provides a mock function with given fields: ctx
func (_m *CredentialsProvider) Retrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialsProvider_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type CredentialsProvider_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CredentialsProvider_Expecter) Retrieve(ctx interface{}) *CredentialsProvider_Retrieve_Call {
	return &CredentialsProvider_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx)}
}

func (_c *CredentialsProvider_Retrieve_Call) Run(run func(ctx context.Context)) *CredentialsProvider_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CredentialsProvider_Retrieve_Call) Return(_a0 aws.Credentials, _a1 error) *CredentialsProvider_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredentialsProvider_Retrieve_Call) RunAndReturn(run func(context.Context) (aws.Credentials, error)) *CredentialsProvider_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// NewCredentialsProvider creates a new instance of CredentialsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsProvider {
	mock := &CredentialsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
