// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	context "context"

	aws "github.com/aws/aws-sdk-go-v2/aws"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IRemoteProvider is an autogenerated mock type for the IRemoteProvider type
type IRemoteProvider struct {
	mock.Mock
}

type IRemoteProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *IRemoteProvider) EXPECT() *IRemoteProvider_Expecter {
	return &IRemoteProvider_Expecter{mock: &_m.Mock}
}

// CredentialSource provides a mock function with no fields
func (_m *IRemoteProvider) CredentialSource() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialSource")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IRemoteProvider_CredentialSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialSource'
type IRemoteProvider_CredentialSource_Call struct {
	*mock.Call
}

// CredentialSource is a helper method to define mock.On call
func (_e *IRemoteProvider_Expecter) CredentialSource() *IRemoteProvider_CredentialSource_Call {
	return &IRemoteProvider_CredentialSource_Call{Call: _e.mock.On("CredentialSource")}
}

func (_c *IRemoteProvider_CredentialSource_Call) Run(run func()) *IRemoteProvider_CredentialSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRemoteProvider_CredentialSource_Call) Return(_a0 string) *IRemoteProvider_CredentialSource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRemoteProvider_CredentialSource_Call) RunAndReturn(run func() string) *IRemoteProvider_CredentialSource_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteExpiresAt provides a mock function with no fields
func (_m *IRemoteProvider) RemoteExpiresAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteExpiresAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// IRemoteProvider_RemoteExpiresAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteExpiresAt'
type IRemoteProvider_RemoteExpiresAt_Call struct {
	*mock.Call
}

// RemoteExpiresAt is a helper method to define mock.On call
func (_e *IRemoteProvider_Expecter) RemoteExpiresAt() *IRemoteProvider_RemoteExpiresAt_Call {
	return &IRemoteProvider_RemoteExpiresAt_Call{Call: _e.mock.On("RemoteExpiresAt")}
}

func (_c *IRemoteProvider_RemoteExpiresAt_Call) Run(run func()) *IRemoteProvider_RemoteExpiresAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRemoteProvider_RemoteExpiresAt_Call) Return(_a0 time.Time) *IRemoteProvider_RemoteExpiresAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRemoteProvider_RemoteExpiresAt_Call) RunAndReturn(run func() time.Time) *IRemoteProvider_RemoteExpiresAt_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteRetrieve provides a mock function with given fields: ctx
func (_m *IRemoteProvider) RemoteRetrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RemoteRetrieve")
	}

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IRemoteProvider_RemoteRetrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteRetrieve'
type IRemoteProvider_RemoteRetrieve_Call struct {
	*mock.Call
}

// RemoteRetrieve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IRemoteProvider_Expecter) RemoteRetrieve(ctx interface{}) *IRemoteProvider_RemoteRetrieve_Call {
	return &IRemoteProvider_RemoteRetrieve_Call{Call: _e.mock.On("RemoteRetrieve", ctx)}
}

func (_c *IRemoteProvider_RemoteRetrieve_Call) Run(run func(ctx context.Context)) *IRemoteProvider_RemoteRetrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IRemoteProvider_RemoteRetrieve_Call) Return(_a0 aws.Credentials, _a1 error) *IRemoteProvider_RemoteRetrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IRemoteProvider_RemoteRetrieve_Call) RunAndReturn(run func(context.Context) (aws.Credentials, error)) *IRemoteProvider_RemoteRetrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ctx
func (_m *IRemoteProvider) Retrieve(ctx context.Context) (aws.Credentials, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 aws.Credentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Credentials, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Credentials); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IRemoteProvider_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type IRemoteProvider_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IRemoteProvider_Expecter) Retrieve(ctx interface{}) *IRemoteProvider_Retrieve_Call {
	return &IRemoteProvider_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx)}
}

func (_c *IRemoteProvider_Retrieve_Call) Run(run func(ctx context.Context)) *IRemoteProvider_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IRemoteProvider_Retrieve_Call) Return(_a0 aws.Credentials, _a1 error) *IRemoteProvider_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IRemoteProvider_Retrieve_Call) RunAndReturn(run func(context.Context) (aws.Credentials, error)) *IRemoteProvider_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// ShareFile provides a mock function with no fields
func (_m *IRemoteProvider) ShareFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShareFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IRemoteProvider_ShareFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareFile'
type IRemoteProvider_ShareFile_Call struct {
	*mock.Call
}

// ShareFile is a helper method to define mock.On call
func (_e *IRemoteProvider_Expecter) ShareFile() *IRemoteProvider_ShareFile_Call {
	return &IRemoteProvider_ShareFile_Call{Call: _e.mock.On("ShareFile")}
}

func (_c *IRemoteProvider_ShareFile_Call) Run(run func()) *IRemoteProvider_ShareFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRemoteProvider_ShareFile_Call) Return(_a0 string) *IRemoteProvider_ShareFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRemoteProvider_ShareFile_Call) RunAndReturn(run func() string) *IRemoteProvider_ShareFile_Call {
	_c.Call.Return(run)
	return _c
}

// ShareProfile provides a mock function with no fields
func (_m *IRemoteProvider) ShareProfile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShareProfile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IRemoteProvider_ShareProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareProfile'
type IRemoteProvider_ShareProfile_Call struct {
	*mock.Call
}

// ShareProfile is a helper method to define mock.On call
func (_e *IRemoteProvider_Expecter) ShareProfile() *IRemoteProvider_ShareProfile_Call {
	return &IRemoteProvider_ShareProfile_Call{Call: _e.mock.On("ShareProfile")}
}

func (_c *IRemoteProvider_ShareProfile_Call) Run(run func()) *IRemoteProvider_ShareProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRemoteProvider_ShareProfile_Call) Return(_a0 string) *IRemoteProvider_ShareProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRemoteProvider_ShareProfile_Call) RunAndReturn(run func() string) *IRemoteProvider_ShareProfile_Call {
	_c.Call.Return(run)
	return _c
}

// SharesCredentials provides a mock function with no fields
func (_m *IRemoteProvider) SharesCredentials() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SharesCredentials")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IRemoteProvider_SharesCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SharesCredentials'
type IRemoteProvider_SharesCredentials_Call struct {
	*mock.Call
}

// SharesCredentials is a helper method to define mock.On call
func (_e *IRemoteProvider_Expecter) SharesCredentials() *IRemoteProvider_SharesCredentials_Call {
	return &IRemoteProvider_SharesCredentials_Call{Call: _e.mock.On("SharesCredentials")}
}

func (_c *IRemoteProvider_SharesCredentials_Call) Run(run func()) *IRemoteProvider_SharesCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRemoteProvider_SharesCredentials_Call) Return(_a0 bool) *IRemoteProvider_SharesCredentials_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRemoteProvider_SharesCredentials_Call) RunAndReturn(run func() bool) *IRemoteProvider_SharesCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRemoteProvider creates a new instance of IRemoteProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRemoteProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRemoteProvider {
	mock := &IRemoteProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
