// Code generated by mockery v2.50.2. DO NOT EDIT.

package cloudwatchlogspublisher

import (
	cont "context"

	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	"github.com/stretchr/testify/mock"
)

// CloudWatchLogsClientMock is an autogenerated mock type for the CloudWatchLogsClient type
type CloudWatchLogsClientMock struct {
	mock.Mock
}

type CloudWatchLogsClientMock_Expecter struct {
	mock *mock.Mock
}

func (m *CloudWatchLogsClientMock) EXPECT() *CloudWatchLogsClientMock_Expecter {
	return &CloudWatchLogsClientMock_Expecter{mock: &m.Mock}
}

// CreateLogGroup provides a mock function with given fields: ctx, params, optFns
func (m *CloudWatchLogsClientMock) CreateLogGroup(ctx cont.Context, params *cloudwatchlogs.CreateLogGroupInput, optFns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogGroupOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogGroup")
	}

	var r0 *cloudwatchlogs.CreateLogGroupOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.CreateLogGroupInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogGroupOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.CreateLogGroupInput, ...func(*cloudwatchlogs.Options)) *cloudwatchlogs.CreateLogGroupOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.CreateLogGroupOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(cont.Context, *cloudwatchlogs.CreateLogGroupInput, ...func(*cloudwatchlogs.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLogStream provides a mock function with given fields: ctx, params, optFns
func (m *CloudWatchLogsClientMock) CreateLogStream(ctx cont.Context, params *cloudwatchlogs.CreateLogStreamInput, optFns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogStreamOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateLogStream")
	}

	var r0 *cloudwatchlogs.CreateLogStreamOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.CreateLogStreamInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.CreateLogStreamOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.CreateLogStreamInput, ...func(*cloudwatchlogs.Options)) *cloudwatchlogs.CreateLogStreamOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.CreateLogStreamOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(cont.Context, *cloudwatchlogs.CreateLogStreamInput, ...func(*cloudwatchlogs.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeLogGroups provides a mock function with given fields: ctx, params, optFns
func (m *CloudWatchLogsClientMock) DescribeLogGroups(ctx cont.Context, params *cloudwatchlogs.DescribeLogGroupsInput, optFns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DescribeLogGroups")
	}

	var r0 *cloudwatchlogs.DescribeLogGroupsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) *cloudwatchlogs.DescribeLogGroupsOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.DescribeLogGroupsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(cont.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DescribeLogStreams provides a mock function with given fields: ctx, params, optFns
func (m *CloudWatchLogsClientMock) DescribeLogStreams(ctx cont.Context, params *cloudwatchlogs.DescribeLogStreamsInput, optFns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogStreamsOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DescribeLogStreams")
	}

	var r0 *cloudwatchlogs.DescribeLogStreamsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.DescribeLogStreamsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogStreamsOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.DescribeLogStreamsInput, ...func(*cloudwatchlogs.Options)) *cloudwatchlogs.DescribeLogStreamsOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.DescribeLogStreamsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(cont.Context, *cloudwatchlogs.DescribeLogStreamsInput, ...func(*cloudwatchlogs.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutLogEvents provides a mock function with given fields: ctx, params, optFns
func (m *CloudWatchLogsClientMock) PutLogEvents(ctx cont.Context, params *cloudwatchlogs.PutLogEventsInput, optFns ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutLogEventsOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutLogEvents")
	}

	var r0 *cloudwatchlogs.PutLogEventsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.PutLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.PutLogEventsOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(cont.Context, *cloudwatchlogs.PutLogEventsInput, ...func(*cloudwatchlogs.Options)) *cloudwatchlogs.PutLogEventsOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cloudwatchlogs.PutLogEventsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(cont.Context, *cloudwatchlogs.PutLogEventsInput, ...func(*cloudwatchlogs.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCloudWatchLogsClientMock creates a new instance of CloudWatchLogsClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCloudWatchLogsClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudWatchLogsClientMock {
	mock := &CloudWatchLogsClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CloudWatchLogsServiceMock is an autogenerated mock type for the ICloudWatchLogsService type
type CloudWatchLogsServiceMock struct {
	mock.Mock
}

type CloudWatchLogsServiceMock_Expecter struct {
	mock *mock.Mock
}

func (m *CloudWatchLogsServiceMock) EXPECT() *CloudWatchLogsServiceMock_Expecter {
	return &CloudWatchLogsServiceMock_Expecter{mock: &m.Mock}
}

// CreateLogGroup provides a mock function with given fields: logGroup
func (m *CloudWatchLogsServiceMock) CreateLogGroup(logGroup string) error {
	ret := m.Called(logGroup)
	return ret.Error(0)
}

// CreateLogStream provides a mock function with given fields: logGroup, logStream
func (m *CloudWatchLogsServiceMock) CreateLogStream(logGroup string, logStream string) error {
	ret := m.Called(logGroup, logStream)
	return ret.Error(0)
}

// CreateNewServiceIfUnHealthy provides a mock function with no fields
func (m *CloudWatchLogsServiceMock) CreateNewServiceIfUnHealthy() {
	m.Called()
}

// DescribeLogGroups provides a mock function with given fields: logGroupPrefix, nextToken
func (m *CloudWatchLogsServiceMock) DescribeLogGroups(logGroupPrefix string, nextToken string) (*cloudwatchlogs.DescribeLogGroupsOutput, error) {
	ret := m.Called(logGroupPrefix, nextToken)
	return ret.Get(0).(*cloudwatchlogs.DescribeLogGroupsOutput), ret.Error(1)
}

// DescribeLogStreams provides a mock function with given fields: logGroup, logStreamPrefix, nextToken
func (m *CloudWatchLogsServiceMock) DescribeLogStreams(logGroup string, logStreamPrefix string, nextToken string) (*cloudwatchlogs.DescribeLogStreamsOutput, error) {
	ret := m.Called(logGroup, logStreamPrefix, nextToken)
	return ret.Get(0).(*cloudwatchlogs.DescribeLogStreamsOutput), ret.Error(1)
}

// GetSequenceTokenForStream provides a mock function with given fields: logGroupName, logStreamName
func (m *CloudWatchLogsServiceMock) GetSequenceTokenForStream(logGroupName string, logStreamName string) *string {
	ret := m.Called(logGroupName, logStreamName)
	if ret.Get(0) == nil {
		return nil
	}
	return ret.Get(0).(*string)
}

// IsLogGroupEncryptedWithKMS provides a mock function with given fields: logGroup
func (m *CloudWatchLogsServiceMock) IsLogGroupEncryptedWithKMS(logGroup *types.LogGroup) (bool, error) {
	ret := m.Called(logGroup)
	return ret.Get(0).(bool), ret.Error(1)
}

// IsLogGroupPresent provides a mock function with given fields: logGroup
func (m *CloudWatchLogsServiceMock) IsLogGroupPresent(logGroup string) (bool, *types.LogGroup) {
	ret := m.Called(logGroup)
	return ret.Bool(0), ret.Get(1).(*types.LogGroup)
}

// IsLogStreamPresent provides a mock function with given fields: logGroupName, logStreamName
func (m *CloudWatchLogsServiceMock) IsLogStreamPresent(logGroupName string, logStreamName string) bool {
	ret := m.Called(logGroupName, logStreamName)
	return ret.Bool(0)
}

// PutLogEvents provides a mock function with given fields: messages, logGroup, logStream, sequenceToken
func (m *CloudWatchLogsServiceMock) PutLogEvents(messages []types.InputLogEvent, logGroup string, logStream string, sequenceToken *string) (*string, error) {
	ret := m.Called(messages, logGroup, logStream, sequenceToken)
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).(*string), ret.Error(1)
}

// SetCloudWatchMessage provides a mock function with given fields: eventVersion, awsRegion, targetId, runAsUser, sessionId, sessionOwner
func (m *CloudWatchLogsServiceMock) SetCloudWatchMessage(eventVersion string, awsRegion string, targetId string, runAsUser string, sessionId string, sessionOwner string) {
	m.Called(eventVersion, awsRegion, targetId, runAsUser, sessionId, sessionOwner)
}

// StreamData provides a mock function with given fields: logGroupName, logStreamName, absoluteFilePath, isFileComplete, isLogStreamCreated, fileCompleteSignal, cleanupControlCharacters, structuredLogs
func (m *CloudWatchLogsServiceMock) StreamData(logGroupName string, logStreamName string, absoluteFilePath string, isFileComplete bool, isLogStreamCreated bool, fileCompleteSignal chan bool, cleanupControlCharacters bool, structuredLogs bool) bool {
	ret := m.Called(logGroupName, logStreamName, absoluteFilePath, isFileComplete, isLogStreamCreated, fileCompleteSignal, cleanupControlCharacters, structuredLogs)
	return ret.Bool(0)
}

// NewCloudWatchLogsServiceMock creates a new instance of CloudWatchLogsServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCloudWatchLogsServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CloudWatchLogsServiceMock {
	mock := &CloudWatchLogsServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NewClientMockDefault returns an instance of CloudWatchLogsClientMock with default expectations set.
func NewClientMockDefault() *CloudWatchLogsClientMock {
	return new(CloudWatchLogsClientMock)
}

// NewServiceMockDefault returns an instance of CloudWatchLogsServiceMock with default expectations set.
func NewServiceMockDefault() *CloudWatchLogsServiceMock {
	mock := new(CloudWatchLogsServiceMock)
	mock.On("CreateNewServiceIfUnHealthy").Return()
	return mock
}
