// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Ec2Detector is an autogenerated mock type for the Ec2Detector type
type Ec2Detector struct {
	mock.Mock
}

// IsEC2Instance provides a mock function with no fields
func (_m *Ec2Detector) IsEC2Instance() (bool, []string) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEC2Instance")
	}

	var r0 bool
	var r1 []string
	if rf, ok := ret.Get(0).(func() (bool, []string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() []string); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	return r0, r1
}

// NewEc2Detector creates a new instance of Ec2Detector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEc2Detector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Ec2Detector {
	mock := &Ec2Detector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
