// Code generated by mockery v2.50.2. DO NOT EDIT.

package mocks

import (
	appconfig "github.com/aws/amazon-ssm-agent/agent/appconfig"
	authtokenrequest "github.com/aws/amazon-ssm-agent/agent/ssm/authtokenrequest"

	aws "github.com/aws/aws-sdk-go-v2/aws"

	credentials "github.com/aws/aws-sdk-go-v2/credentials"

	log "github.com/aws/amazon-ssm-agent/agent/log"

	mock "github.com/stretchr/testify/mock"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"

	testing "testing"
)

// IRsaClientDeps is an autogenerated mock type for the IRsaClientDeps type
type IRsaClientDeps struct {
	mock.Mock
}

// AwsConfig provides a mock function with given fields: _a0, appConfig, service, region
func (_m *IRsaClientDeps) AwsConfig(_a0 log.T, appConfig appconfig.SsmagentConfig, service string, region string) aws.Config {
	ret := _m.Called(_a0, appConfig, service, region)

	var r0 aws.Config
	if rf, ok := ret.Get(0).(func(log.T, appconfig.SsmagentConfig, string, string) aws.Config); ok {
		r0 = rf(_a0, appConfig, service, region)
	} else {
		r0 = ret.Get(0).(aws.Config)
	}

	return r0
}

// NewAuthTokenClient provides a mock function with given fields: sdk
func (_m *IRsaClientDeps) NewAuthTokenClient(sdk *ssm.Client) authtokenrequest.IClient {
	ret := _m.Called(sdk)

	var r0 authtokenrequest.IClient
	if rf, ok := ret.Get(0).(func(*ssm.Client) authtokenrequest.IClient); ok {
		r0 = rf(sdk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authtokenrequest.IClient)
		}
	}

	return r0
}

// NewCredentials provides a mock function with given fields: provider
func (_m *IRsaClientDeps) NewCredentials(provider credentials.StaticCredentialsProvider) aws.Credentials {
	ret := _m.Called(provider)

	var r0 aws.Credentials
	if rf, ok := ret.Get(0).(func(credentials.StaticCredentialsProvider) aws.Credentials); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	return r0
}

// NewSsmSdk provides a mock function with given fields: cfgs
func (_m *IRsaClientDeps) NewSsmSdk(cfgs aws.Config) *ssm.Client {
	ret := _m.Called(cfgs)

	var r0 *ssm.Client
	if rf, ok := ret.Get(0).(func(aws.Config) *ssm.Client); ok {
		r0 = rf(cfgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.Client)
		}
	}

	return r0
}

// NewStaticCredentials provides a mock function with given fields: id, secret, token
func (_m *IRsaClientDeps) NewStaticCredentials(id string, secret string, token string) aws.Credentials {
	ret := _m.Called(id, secret, token)

	var r0 aws.Credentials
	if rf, ok := ret.Get(0).(func(string, string, string) aws.Credentials); ok {
		r0 = rf(id, secret, token)
	} else {
		r0 = ret.Get(0).(aws.Credentials)
	}

	return r0
}

// NewStaticCredentialsProvider provides a mock function with given fields: id, secret, token
func (_m *IRsaClientDeps) NewStaticCredentialsProvider(id string, secret string, token string) credentials.StaticCredentialsProvider {
	ret := _m.Called(id, secret, token)

	var r0 credentials.StaticCredentialsProvider
	if rf, ok := ret.Get(0).(func(string, string, string) credentials.StaticCredentialsProvider); ok {
		r0 = rf(id, secret, token)
	} else {
		r0 = ret.Get(0).(credentials.StaticCredentialsProvider)
	}

	return r0
}

// NewIRsaClientDeps creates a new instance of IRsaClientDeps. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRsaClientDeps(t testing.TB) *IRsaClientDeps {
	mock := &IRsaClientDeps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
