// Code generated by mockery v2.50.2. DO NOT EDIT.

package authtokenrequest

import (
	context "context"

	ssm "github.com/aws/aws-sdk-go-v2/service/ssm"
	mock "github.com/stretchr/testify/mock"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

type IClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IClient) EXPECT() *IClient_Expecter {
	return &IClient_Expecter{mock: &_m.Mock}
}

// RequestManagedInstanceRoleToken provides a mock function with given fields: fingerprint
func (_m *IClient) RequestManagedInstanceRoleToken(fingerprint string) (*ssm.RequestManagedInstanceRoleTokenOutput, error) {
	ret := _m.Called(fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for RequestManagedInstanceRoleToken")
	}

	var r0 *ssm.RequestManagedInstanceRoleTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ssm.RequestManagedInstanceRoleTokenOutput, error)); ok {
		return rf(fingerprint)
	}
	if rf, ok := ret.Get(0).(func(string) *ssm.RequestManagedInstanceRoleTokenOutput); ok {
		r0 = rf(fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RequestManagedInstanceRoleTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClient_RequestManagedInstanceRoleToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestManagedInstanceRoleToken'
type IClient_RequestManagedInstanceRoleToken_Call struct {
	*mock.Call
}

// RequestManagedInstanceRoleToken is a helper method to define mock.On call
//   - fingerprint string
func (_e *IClient_Expecter) RequestManagedInstanceRoleToken(fingerprint interface{}) *IClient_RequestManagedInstanceRoleToken_Call {
	return &IClient_RequestManagedInstanceRoleToken_Call{Call: _e.mock.On("RequestManagedInstanceRoleToken", fingerprint)}
}

func (_c *IClient_RequestManagedInstanceRoleToken_Call) Run(run func(fingerprint string)) *IClient_RequestManagedInstanceRoleToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *IClient_RequestManagedInstanceRoleToken_Call) Return(response *ssm.RequestManagedInstanceRoleTokenOutput, err error) *IClient_RequestManagedInstanceRoleToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *IClient_RequestManagedInstanceRoleToken_Call) RunAndReturn(run func(string) (*ssm.RequestManagedInstanceRoleTokenOutput, error)) *IClient_RequestManagedInstanceRoleToken_Call {
	_c.Call.Return(run)
	return _c
}

// RequestManagedInstanceRoleTokenWithContext provides a mock function with given fields: ctx, fingerprint
func (_m *IClient) RequestManagedInstanceRoleTokenWithContext(ctx context.Context, fingerprint string) (*ssm.RequestManagedInstanceRoleTokenOutput, error) {
	ret := _m.Called(ctx, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for RequestManagedInstanceRoleTokenWithContext")
	}

	var r0 *ssm.RequestManagedInstanceRoleTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ssm.RequestManagedInstanceRoleTokenOutput, error)); ok {
		return rf(ctx, fingerprint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ssm.RequestManagedInstanceRoleTokenOutput); ok {
		r0 = rf(ctx, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RequestManagedInstanceRoleTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClient_RequestManagedInstanceRoleTokenWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestManagedInstanceRoleTokenWithContext'
type IClient_RequestManagedInstanceRoleTokenWithContext_Call struct {
	*mock.Call
}

// RequestManagedInstanceRoleTokenWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - fingerprint string
func (_e *IClient_Expecter) RequestManagedInstanceRoleTokenWithContext(ctx interface{}, fingerprint interface{}) *IClient_RequestManagedInstanceRoleTokenWithContext_Call {
	return &IClient_RequestManagedInstanceRoleTokenWithContext_Call{Call: _e.mock.On("RequestManagedInstanceRoleTokenWithContext", ctx, fingerprint)}
}

func (_c *IClient_RequestManagedInstanceRoleTokenWithContext_Call) Run(run func(ctx context.Context, fingerprint string)) *IClient_RequestManagedInstanceRoleTokenWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IClient_RequestManagedInstanceRoleTokenWithContext_Call) Return(response *ssm.RequestManagedInstanceRoleTokenOutput, err error) *IClient_RequestManagedInstanceRoleTokenWithContext_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *IClient_RequestManagedInstanceRoleTokenWithContext_Call) RunAndReturn(run func(context.Context, string) (*ssm.RequestManagedInstanceRoleTokenOutput, error)) *IClient_RequestManagedInstanceRoleTokenWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateManagedInstancePublicKey provides a mock function with given fields: publicKey, publicKeyType
func (_m *IClient) UpdateManagedInstancePublicKey(publicKey string, publicKeyType string) (*ssm.UpdateManagedInstancePublicKeyOutput, error) {
	ret := _m.Called(publicKey, publicKeyType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManagedInstancePublicKey")
	}

	var r0 *ssm.UpdateManagedInstancePublicKeyOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*ssm.UpdateManagedInstancePublicKeyOutput, error)); ok {
		return rf(publicKey, publicKeyType)
	}
	if rf, ok := ret.Get(0).(func(string, string) *ssm.UpdateManagedInstancePublicKeyOutput); ok {
		r0 = rf(publicKey, publicKeyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.UpdateManagedInstancePublicKeyOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(publicKey, publicKeyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClient_UpdateManagedInstancePublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateManagedInstancePublicKey'
type IClient_UpdateManagedInstancePublicKey_Call struct {
	*mock.Call
}

// UpdateManagedInstancePublicKey is a helper method to define mock.On call
//   - publicKey string
//   - publicKeyType string
func (_e *IClient_Expecter) UpdateManagedInstancePublicKey(publicKey interface{}, publicKeyType interface{}) *IClient_UpdateManagedInstancePublicKey_Call {
	return &IClient_UpdateManagedInstancePublicKey_Call{Call: _e.mock.On("UpdateManagedInstancePublicKey", publicKey, publicKeyType)}
}

func (_c *IClient_UpdateManagedInstancePublicKey_Call) Run(run func(publicKey string, publicKeyType string)) *IClient_UpdateManagedInstancePublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *IClient_UpdateManagedInstancePublicKey_Call) Return(response *ssm.UpdateManagedInstancePublicKeyOutput, err error) *IClient_UpdateManagedInstancePublicKey_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *IClient_UpdateManagedInstancePublicKey_Call) RunAndReturn(run func(string, string) (*ssm.UpdateManagedInstancePublicKeyOutput, error)) *IClient_UpdateManagedInstancePublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateManagedInstancePublicKeyWithContext provides a mock function with given fields: ctx, publicKey, publicKeyType
func (_m *IClient) UpdateManagedInstancePublicKeyWithContext(ctx context.Context, publicKey string, publicKeyType string) (*ssm.UpdateManagedInstancePublicKeyOutput, error) {
	ret := _m.Called(ctx, publicKey, publicKeyType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManagedInstancePublicKeyWithContext")
	}

	var r0 *ssm.UpdateManagedInstancePublicKeyOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*ssm.UpdateManagedInstancePublicKeyOutput, error)); ok {
		return rf(ctx, publicKey, publicKeyType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ssm.UpdateManagedInstancePublicKeyOutput); ok {
		r0 = rf(ctx, publicKey, publicKeyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.UpdateManagedInstancePublicKeyOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, publicKey, publicKeyType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IClient_UpdateManagedInstancePublicKeyWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateManagedInstancePublicKeyWithContext'
type IClient_UpdateManagedInstancePublicKeyWithContext_Call struct {
	*mock.Call
}

// UpdateManagedInstancePublicKeyWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - publicKey string
//   - publicKeyType string
func (_e *IClient_Expecter) UpdateManagedInstancePublicKeyWithContext(ctx interface{}, publicKey interface{}, publicKeyType interface{}) *IClient_UpdateManagedInstancePublicKeyWithContext_Call {
	return &IClient_UpdateManagedInstancePublicKeyWithContext_Call{Call: _e.mock.On("UpdateManagedInstancePublicKeyWithContext", ctx, publicKey, publicKeyType)}
}

func (_c *IClient_UpdateManagedInstancePublicKeyWithContext_Call) Run(run func(ctx context.Context, publicKey string, publicKeyType string)) *IClient_UpdateManagedInstancePublicKeyWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *IClient_UpdateManagedInstancePublicKeyWithContext_Call) Return(response *ssm.UpdateManagedInstancePublicKeyOutput, err error) *IClient_UpdateManagedInstancePublicKeyWithContext_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *IClient_UpdateManagedInstancePublicKeyWithContext_Call) RunAndReturn(run func(context.Context, string, string) (*ssm.UpdateManagedInstancePublicKeyOutput, error)) *IClient_UpdateManagedInstancePublicKeyWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
